// GENERATED FILE - DO NOT EDIT.
// Source: https://www.unicode.org/Public/emoji/latest/emoji-test.txt
// Unicode Emoji Version: 17.0

import 'package:emoji_picker_flutter/emoji_picker_flutter.dart';

const List<CategoryEmoji> latestEmojiSet = [
  CategoryEmoji(Category.SMILEYS, [
    Emoji('😀', 'grinning face'),
    Emoji('😃', 'grinning face with big eyes'),
    Emoji('😄', 'grinning face with smiling eyes'),
    Emoji('😁', 'beaming face with smiling eyes'),
    Emoji('😆', 'grinning squinting face'),
    Emoji('😅', 'grinning face with sweat'),
    Emoji('🤣', 'rolling on the floor laughing'),
    Emoji('😂', 'face with tears of joy'),
    Emoji('🙂', 'slightly smiling face'),
    Emoji('🙃', 'upside-down face'),
    Emoji('🫠', 'melting face'),
    Emoji('😉', 'winking face'),
    Emoji('😊', 'smiling face with smiling eyes'),
    Emoji('😇', 'smiling face with halo'),
    Emoji('🥰', 'smiling face with hearts'),
    Emoji('😍', 'smiling face with heart-eyes'),
    Emoji('🤩', 'star-struck'),
    Emoji('😘', 'face blowing a kiss'),
    Emoji('😗', 'kissing face'),
    Emoji('☺️', 'smiling face'),
    Emoji('😚', 'kissing face with closed eyes'),
    Emoji('😙', 'kissing face with smiling eyes'),
    Emoji('🥲', 'smiling face with tear'),
    Emoji('😋', 'face savoring food'),
    Emoji('😛', 'face with tongue'),
    Emoji('😜', 'winking face with tongue'),
    Emoji('🤪', 'zany face'),
    Emoji('😝', 'squinting face with tongue'),
    Emoji('🤑', 'money-mouth face'),
    Emoji('🤗', 'smiling face with open hands'),
    Emoji('🤭', 'face with hand over mouth'),
    Emoji('🫢', 'face with open eyes and hand over mouth'),
    Emoji('🫣', 'face with peeking eye'),
    Emoji('🤫', 'shushing face'),
    Emoji('🤔', 'thinking face'),
    Emoji('🫡', 'saluting face'),
    Emoji('🤐', 'zipper-mouth face'),
    Emoji('🤨', 'face with raised eyebrow'),
    Emoji('😐', 'neutral face'),
    Emoji('😑', 'expressionless face'),
    Emoji('😶', 'face without mouth'),
    Emoji('🫥', 'dotted line face'),
    Emoji('😶‍🌫️', 'face in clouds'),
    Emoji('😏', 'smirking face'),
    Emoji('😒', 'unamused face'),
    Emoji('🙄', 'face with rolling eyes'),
    Emoji('😬', 'grimacing face'),
    Emoji('😮‍💨', 'face exhaling'),
    Emoji('🤥', 'lying face'),
    Emoji('🫨', 'shaking face'),
    Emoji('🙂‍↔️', 'head shaking horizontally'),
    Emoji('🙂‍↕️', 'head shaking vertically'),
    Emoji('😌', 'relieved face'),
    Emoji('😔', 'pensive face'),
    Emoji('😪', 'sleepy face'),
    Emoji('🤤', 'drooling face'),
    Emoji('😴', 'sleeping face'),
    Emoji('🫩', 'face with bags under eyes'),
    Emoji('😷', 'face with medical mask'),
    Emoji('🤒', 'face with thermometer'),
    Emoji('🤕', 'face with head-bandage'),
    Emoji('🤢', 'nauseated face'),
    Emoji('🤮', 'face vomiting'),
    Emoji('🤧', 'sneezing face'),
    Emoji('🥵', 'hot face'),
    Emoji('🥶', 'cold face'),
    Emoji('🥴', 'woozy face'),
    Emoji('😵', 'face with crossed-out eyes'),
    Emoji('😵‍💫', 'face with spiral eyes'),
    Emoji('🤯', 'exploding head'),
    Emoji('🤠', 'cowboy hat face'),
    Emoji('🥳', 'partying face'),
    Emoji('🥸', 'disguised face'),
    Emoji('😎', 'smiling face with sunglasses'),
    Emoji('🤓', 'nerd face'),
    Emoji('🧐', 'face with monocle'),
    Emoji('😕', 'confused face'),
    Emoji('🫤', 'face with diagonal mouth'),
    Emoji('😟', 'worried face'),
    Emoji('🙁', 'slightly frowning face'),
    Emoji('☹️', 'frowning face'),
    Emoji('😮', 'face with open mouth'),
    Emoji('😯', 'hushed face'),
    Emoji('😲', 'astonished face'),
    Emoji('😳', 'flushed face'),
    Emoji('🫪', 'distorted face'),
    Emoji('🥺', 'pleading face'),
    Emoji('🥹', 'face holding back tears'),
    Emoji('😦', 'frowning face with open mouth'),
    Emoji('😧', 'anguished face'),
    Emoji('😨', 'fearful face'),
    Emoji('😰', 'anxious face with sweat'),
    Emoji('😥', 'sad but relieved face'),
    Emoji('😢', 'crying face'),
    Emoji('😭', 'loudly crying face'),
    Emoji('😱', 'face screaming in fear'),
    Emoji('😖', 'confounded face'),
    Emoji('😣', 'persevering face'),
    Emoji('😞', 'disappointed face'),
    Emoji('😓', 'downcast face with sweat'),
    Emoji('😩', 'weary face'),
    Emoji('😫', 'tired face'),
    Emoji('🥱', 'yawning face'),
    Emoji('😤', 'face with steam from nose'),
    Emoji('😡', 'enraged face'),
    Emoji('😠', 'angry face'),
    Emoji('🤬', 'face with symbols on mouth'),
    Emoji('😈', 'smiling face with horns'),
    Emoji('👿', 'angry face with horns'),
    Emoji('💀', 'skull'),
    Emoji('☠️', 'skull and crossbones'),
    Emoji('💩', 'pile of poo'),
    Emoji('🤡', 'clown face'),
    Emoji('👹', 'ogre'),
    Emoji('👺', 'goblin'),
    Emoji('👻', 'ghost'),
    Emoji('👽', 'alien'),
    Emoji('👾', 'alien monster'),
    Emoji('🤖', 'robot'),
    Emoji('😺', 'grinning cat'),
    Emoji('😸', 'grinning cat with smiling eyes'),
    Emoji('😹', 'cat with tears of joy'),
    Emoji('😻', 'smiling cat with heart-eyes'),
    Emoji('😼', 'cat with wry smile'),
    Emoji('😽', 'kissing cat'),
    Emoji('🙀', 'weary cat'),
    Emoji('😿', 'crying cat'),
    Emoji('😾', 'pouting cat'),
    Emoji('🙈', 'see-no-evil monkey'),
    Emoji('🙉', 'hear-no-evil monkey'),
    Emoji('🙊', 'speak-no-evil monkey'),
    Emoji('💌', 'love letter'),
    Emoji('💘', 'heart with arrow'),
    Emoji('💝', 'heart with ribbon'),
    Emoji('💖', 'sparkling heart'),
    Emoji('💗', 'growing heart'),
    Emoji('💓', 'beating heart'),
    Emoji('💞', 'revolving hearts'),
    Emoji('💕', 'two hearts'),
    Emoji('💟', 'heart decoration'),
    Emoji('❣️', 'heart exclamation'),
    Emoji('💔', 'broken heart'),
    Emoji('❤️‍🔥', 'heart on fire'),
    Emoji('❤️‍🩹', 'mending heart'),
    Emoji('❤️', 'red heart'),
    Emoji('🩷', 'pink heart'),
    Emoji('🧡', 'orange heart'),
    Emoji('💛', 'yellow heart'),
    Emoji('💚', 'green heart'),
    Emoji('💙', 'blue heart'),
    Emoji('🩵', 'light blue heart'),
    Emoji('💜', 'purple heart'),
    Emoji('🤎', 'brown heart'),
    Emoji('🖤', 'black heart'),
    Emoji('🩶', 'grey heart'),
    Emoji('🤍', 'white heart'),
    Emoji('💋', 'kiss mark'),
    Emoji('💯', 'hundred points'),
    Emoji('💢', 'anger symbol'),
    Emoji('🫯', 'fight cloud'),
    Emoji('💥', 'collision'),
    Emoji('💫', 'dizzy'),
    Emoji('💦', 'sweat droplets'),
    Emoji('💨', 'dashing away'),
    Emoji('🕳️', 'hole'),
    Emoji('💬', 'speech balloon'),
    Emoji('👁️‍🗨️', 'eye in speech bubble'),
    Emoji('🗨️', 'left speech bubble'),
    Emoji('🗯️', 'right anger bubble'),
    Emoji('💭', 'thought balloon'),
    Emoji('💤', 'ZZZ'),
    Emoji('👋', 'waving hand', hasSkinTone: true),
    Emoji('🤚', 'raised back of hand', hasSkinTone: true),
    Emoji('🖐️', 'hand with fingers splayed'),
    Emoji('✋', 'raised hand', hasSkinTone: true),
    Emoji('🖖', 'vulcan salute', hasSkinTone: true),
    Emoji('🫱', 'rightwards hand', hasSkinTone: true),
    Emoji('🫲', 'leftwards hand', hasSkinTone: true),
    Emoji('🫳', 'palm down hand', hasSkinTone: true),
    Emoji('🫴', 'palm up hand', hasSkinTone: true),
    Emoji('🫷', 'leftwards pushing hand', hasSkinTone: true),
    Emoji('🫸', 'rightwards pushing hand', hasSkinTone: true),
    Emoji('👌', 'OK hand', hasSkinTone: true),
    Emoji('🤌', 'pinched fingers', hasSkinTone: true),
    Emoji('🤏', 'pinching hand', hasSkinTone: true),
    Emoji('✌️', 'victory hand'),
    Emoji('🤞', 'crossed fingers', hasSkinTone: true),
    Emoji('🫰', 'hand with index finger and thumb crossed', hasSkinTone: true),
    Emoji('🤟', 'love-you gesture', hasSkinTone: true),
    Emoji('🤘', 'sign of the horns', hasSkinTone: true),
    Emoji('🤙', 'call me hand', hasSkinTone: true),
    Emoji('👈', 'backhand index pointing left', hasSkinTone: true),
    Emoji('👉', 'backhand index pointing right', hasSkinTone: true),
    Emoji('👆', 'backhand index pointing up', hasSkinTone: true),
    Emoji('🖕', 'middle finger', hasSkinTone: true),
    Emoji('👇', 'backhand index pointing down', hasSkinTone: true),
    Emoji('☝️', 'index pointing up'),
    Emoji('🫵', 'index pointing at the viewer', hasSkinTone: true),
    Emoji('👍', 'thumbs up', hasSkinTone: true),
    Emoji('👎', 'thumbs down', hasSkinTone: true),
    Emoji('✊', 'raised fist', hasSkinTone: true),
    Emoji('👊', 'oncoming fist', hasSkinTone: true),
    Emoji('🤛', 'left-facing fist', hasSkinTone: true),
    Emoji('🤜', 'right-facing fist', hasSkinTone: true),
    Emoji('👏', 'clapping hands', hasSkinTone: true),
    Emoji('🙌', 'raising hands', hasSkinTone: true),
    Emoji('🫶', 'heart hands', hasSkinTone: true),
    Emoji('👐', 'open hands', hasSkinTone: true),
    Emoji('🤲', 'palms up together', hasSkinTone: true),
    Emoji('🤝', 'handshake', hasSkinTone: true),
    Emoji('🙏', 'folded hands', hasSkinTone: true),
    Emoji('✍️', 'writing hand'),
    Emoji('💅', 'nail polish', hasSkinTone: true),
    Emoji('🤳', 'selfie', hasSkinTone: true),
    Emoji('💪', 'flexed biceps', hasSkinTone: true),
    Emoji('🦾', 'mechanical arm'),
    Emoji('🦿', 'mechanical leg'),
    Emoji('🦵', 'leg', hasSkinTone: true),
    Emoji('🦶', 'foot', hasSkinTone: true),
    Emoji('👂', 'ear', hasSkinTone: true),
    Emoji('🦻', 'ear with hearing aid', hasSkinTone: true),
    Emoji('👃', 'nose', hasSkinTone: true),
    Emoji('🧠', 'brain'),
    Emoji('🫀', 'anatomical heart'),
    Emoji('🫁', 'lungs'),
    Emoji('🦷', 'tooth'),
    Emoji('🦴', 'bone'),
    Emoji('👀', 'eyes'),
    Emoji('👁️', 'eye'),
    Emoji('👅', 'tongue'),
    Emoji('👄', 'mouth'),
    Emoji('🫦', 'biting lip'),
    Emoji('👶', 'baby', hasSkinTone: true),
    Emoji('🧒', 'child', hasSkinTone: true),
    Emoji('👦', 'boy', hasSkinTone: true),
    Emoji('👧', 'girl', hasSkinTone: true),
    Emoji('🧑', 'person', hasSkinTone: true),
    Emoji('👱', 'person: blond hair', hasSkinTone: true),
    Emoji('👨', 'man', hasSkinTone: true),
    Emoji('🧔', 'person: beard', hasSkinTone: true),
    Emoji('🧔‍♂️', 'man: beard', hasSkinTone: true),
    Emoji('🧔‍♀️', 'woman: beard', hasSkinTone: true),
    Emoji('👨‍🦰', 'man: red hair', hasSkinTone: true),
    Emoji('👨‍🦱', 'man: curly hair', hasSkinTone: true),
    Emoji('👨‍🦳', 'man: white hair', hasSkinTone: true),
    Emoji('👨‍🦲', 'man: bald', hasSkinTone: true),
    Emoji('👩', 'woman', hasSkinTone: true),
    Emoji('👩‍🦰', 'woman: red hair', hasSkinTone: true),
    Emoji('🧑‍🦰', 'person: red hair', hasSkinTone: true),
    Emoji('👩‍🦱', 'woman: curly hair', hasSkinTone: true),
    Emoji('🧑‍🦱', 'person: curly hair', hasSkinTone: true),
    Emoji('👩‍🦳', 'woman: white hair', hasSkinTone: true),
    Emoji('🧑‍🦳', 'person: white hair', hasSkinTone: true),
    Emoji('👩‍🦲', 'woman: bald', hasSkinTone: true),
    Emoji('🧑‍🦲', 'person: bald', hasSkinTone: true),
    Emoji('👱‍♀️', 'woman: blond hair', hasSkinTone: true),
    Emoji('👱‍♂️', 'man: blond hair', hasSkinTone: true),
    Emoji('🧓', 'older person', hasSkinTone: true),
    Emoji('👴', 'old man', hasSkinTone: true),
    Emoji('👵', 'old woman', hasSkinTone: true),
    Emoji('🙍', 'person frowning', hasSkinTone: true),
    Emoji('🙍‍♂️', 'man frowning', hasSkinTone: true),
    Emoji('🙍‍♀️', 'woman frowning', hasSkinTone: true),
    Emoji('🙎', 'person pouting', hasSkinTone: true),
    Emoji('🙎‍♂️', 'man pouting', hasSkinTone: true),
    Emoji('🙎‍♀️', 'woman pouting', hasSkinTone: true),
    Emoji('🙅', 'person gesturing NO', hasSkinTone: true),
    Emoji('🙅‍♂️', 'man gesturing NO', hasSkinTone: true),
    Emoji('🙅‍♀️', 'woman gesturing NO', hasSkinTone: true),
    Emoji('🙆', 'person gesturing OK', hasSkinTone: true),
    Emoji('🙆‍♂️', 'man gesturing OK', hasSkinTone: true),
    Emoji('🙆‍♀️', 'woman gesturing OK', hasSkinTone: true),
    Emoji('💁', 'person tipping hand', hasSkinTone: true),
    Emoji('💁‍♂️', 'man tipping hand', hasSkinTone: true),
    Emoji('💁‍♀️', 'woman tipping hand', hasSkinTone: true),
    Emoji('🙋', 'person raising hand', hasSkinTone: true),
    Emoji('🙋‍♂️', 'man raising hand', hasSkinTone: true),
    Emoji('🙋‍♀️', 'woman raising hand', hasSkinTone: true),
    Emoji('🧏', 'deaf person', hasSkinTone: true),
    Emoji('🧏‍♂️', 'deaf man', hasSkinTone: true),
    Emoji('🧏‍♀️', 'deaf woman', hasSkinTone: true),
    Emoji('🙇', 'person bowing', hasSkinTone: true),
    Emoji('🙇‍♂️', 'man bowing', hasSkinTone: true),
    Emoji('🙇‍♀️', 'woman bowing', hasSkinTone: true),
    Emoji('🤦', 'person facepalming', hasSkinTone: true),
    Emoji('🤦‍♂️', 'man facepalming', hasSkinTone: true),
    Emoji('🤦‍♀️', 'woman facepalming', hasSkinTone: true),
    Emoji('🤷', 'person shrugging', hasSkinTone: true),
    Emoji('🤷‍♂️', 'man shrugging', hasSkinTone: true),
    Emoji('🤷‍♀️', 'woman shrugging', hasSkinTone: true),
    Emoji('🧑‍⚕️', 'health worker', hasSkinTone: true),
    Emoji('👨‍⚕️', 'man health worker', hasSkinTone: true),
    Emoji('👩‍⚕️', 'woman health worker', hasSkinTone: true),
    Emoji('🧑‍🎓', 'student', hasSkinTone: true),
    Emoji('👨‍🎓', 'man student', hasSkinTone: true),
    Emoji('👩‍🎓', 'woman student', hasSkinTone: true),
    Emoji('🧑‍🏫', 'teacher', hasSkinTone: true),
    Emoji('👨‍🏫', 'man teacher', hasSkinTone: true),
    Emoji('👩‍🏫', 'woman teacher', hasSkinTone: true),
    Emoji('🧑‍⚖️', 'judge', hasSkinTone: true),
    Emoji('👨‍⚖️', 'man judge', hasSkinTone: true),
    Emoji('👩‍⚖️', 'woman judge', hasSkinTone: true),
    Emoji('🧑‍🌾', 'farmer', hasSkinTone: true),
    Emoji('👨‍🌾', 'man farmer', hasSkinTone: true),
    Emoji('👩‍🌾', 'woman farmer', hasSkinTone: true),
    Emoji('🧑‍🍳', 'cook', hasSkinTone: true),
    Emoji('👨‍🍳', 'man cook', hasSkinTone: true),
    Emoji('👩‍🍳', 'woman cook', hasSkinTone: true),
    Emoji('🧑‍🔧', 'mechanic', hasSkinTone: true),
    Emoji('👨‍🔧', 'man mechanic', hasSkinTone: true),
    Emoji('👩‍🔧', 'woman mechanic', hasSkinTone: true),
    Emoji('🧑‍🏭', 'factory worker', hasSkinTone: true),
    Emoji('👨‍🏭', 'man factory worker', hasSkinTone: true),
    Emoji('👩‍🏭', 'woman factory worker', hasSkinTone: true),
    Emoji('🧑‍💼', 'office worker', hasSkinTone: true),
    Emoji('👨‍💼', 'man office worker', hasSkinTone: true),
    Emoji('👩‍💼', 'woman office worker', hasSkinTone: true),
    Emoji('🧑‍🔬', 'scientist', hasSkinTone: true),
    Emoji('👨‍🔬', 'man scientist', hasSkinTone: true),
    Emoji('👩‍🔬', 'woman scientist', hasSkinTone: true),
    Emoji('🧑‍💻', 'technologist', hasSkinTone: true),
    Emoji('👨‍💻', 'man technologist', hasSkinTone: true),
    Emoji('👩‍💻', 'woman technologist', hasSkinTone: true),
    Emoji('🧑‍🎤', 'singer', hasSkinTone: true),
    Emoji('👨‍🎤', 'man singer', hasSkinTone: true),
    Emoji('👩‍🎤', 'woman singer', hasSkinTone: true),
    Emoji('🧑‍🎨', 'artist', hasSkinTone: true),
    Emoji('👨‍🎨', 'man artist', hasSkinTone: true),
    Emoji('👩‍🎨', 'woman artist', hasSkinTone: true),
    Emoji('🧑‍✈️', 'pilot', hasSkinTone: true),
    Emoji('👨‍✈️', 'man pilot', hasSkinTone: true),
    Emoji('👩‍✈️', 'woman pilot', hasSkinTone: true),
    Emoji('🧑‍🚀', 'astronaut', hasSkinTone: true),
    Emoji('👨‍🚀', 'man astronaut', hasSkinTone: true),
    Emoji('👩‍🚀', 'woman astronaut', hasSkinTone: true),
    Emoji('🧑‍🚒', 'firefighter', hasSkinTone: true),
    Emoji('👨‍🚒', 'man firefighter', hasSkinTone: true),
    Emoji('👩‍🚒', 'woman firefighter', hasSkinTone: true),
    Emoji('👮', 'police officer', hasSkinTone: true),
    Emoji('👮‍♂️', 'man police officer', hasSkinTone: true),
    Emoji('👮‍♀️', 'woman police officer', hasSkinTone: true),
    Emoji('🕵️', 'detective'),
    Emoji('🕵️‍♂️', 'man detective'),
    Emoji('🕵️‍♀️', 'woman detective'),
    Emoji('💂', 'guard', hasSkinTone: true),
    Emoji('💂‍♂️', 'man guard', hasSkinTone: true),
    Emoji('💂‍♀️', 'woman guard', hasSkinTone: true),
    Emoji('🥷', 'ninja', hasSkinTone: true),
    Emoji('👷', 'construction worker', hasSkinTone: true),
    Emoji('👷‍♂️', 'man construction worker', hasSkinTone: true),
    Emoji('👷‍♀️', 'woman construction worker', hasSkinTone: true),
    Emoji('🫅', 'person with crown', hasSkinTone: true),
    Emoji('🤴', 'prince', hasSkinTone: true),
    Emoji('👸', 'princess', hasSkinTone: true),
    Emoji('👳', 'person wearing turban', hasSkinTone: true),
    Emoji('👳‍♂️', 'man wearing turban', hasSkinTone: true),
    Emoji('👳‍♀️', 'woman wearing turban', hasSkinTone: true),
    Emoji('👲', 'person with skullcap', hasSkinTone: true),
    Emoji('🧕', 'woman with headscarf', hasSkinTone: true),
    Emoji('🤵', 'person in tuxedo', hasSkinTone: true),
    Emoji('🤵‍♂️', 'man in tuxedo', hasSkinTone: true),
    Emoji('🤵‍♀️', 'woman in tuxedo', hasSkinTone: true),
    Emoji('👰', 'person with veil', hasSkinTone: true),
    Emoji('👰‍♂️', 'man with veil', hasSkinTone: true),
    Emoji('👰‍♀️', 'woman with veil', hasSkinTone: true),
    Emoji('🤰', 'pregnant woman', hasSkinTone: true),
    Emoji('🫃', 'pregnant man', hasSkinTone: true),
    Emoji('🫄', 'pregnant person', hasSkinTone: true),
    Emoji('🤱', 'breast-feeding', hasSkinTone: true),
    Emoji('👩‍🍼', 'woman feeding baby', hasSkinTone: true),
    Emoji('👨‍🍼', 'man feeding baby', hasSkinTone: true),
    Emoji('🧑‍🍼', 'person feeding baby', hasSkinTone: true),
    Emoji('👼', 'baby angel', hasSkinTone: true),
    Emoji('🎅', 'Santa Claus', hasSkinTone: true),
    Emoji('🤶', 'Mrs. Claus', hasSkinTone: true),
    Emoji('🧑‍🎄', 'Mx Claus', hasSkinTone: true),
    Emoji('🦸', 'superhero', hasSkinTone: true),
    Emoji('🦸‍♂️', 'man superhero', hasSkinTone: true),
    Emoji('🦸‍♀️', 'woman superhero', hasSkinTone: true),
    Emoji('🦹', 'supervillain', hasSkinTone: true),
    Emoji('🦹‍♂️', 'man supervillain', hasSkinTone: true),
    Emoji('🦹‍♀️', 'woman supervillain', hasSkinTone: true),
    Emoji('🧙', 'mage', hasSkinTone: true),
    Emoji('🧙‍♂️', 'man mage', hasSkinTone: true),
    Emoji('🧙‍♀️', 'woman mage', hasSkinTone: true),
    Emoji('🧚', 'fairy', hasSkinTone: true),
    Emoji('🧚‍♂️', 'man fairy', hasSkinTone: true),
    Emoji('🧚‍♀️', 'woman fairy', hasSkinTone: true),
    Emoji('🧛', 'vampire', hasSkinTone: true),
    Emoji('🧛‍♂️', 'man vampire', hasSkinTone: true),
    Emoji('🧛‍♀️', 'woman vampire', hasSkinTone: true),
    Emoji('🧜', 'merperson', hasSkinTone: true),
    Emoji('🧜‍♂️', 'merman', hasSkinTone: true),
    Emoji('🧜‍♀️', 'mermaid', hasSkinTone: true),
    Emoji('🧝', 'elf', hasSkinTone: true),
    Emoji('🧝‍♂️', 'man elf', hasSkinTone: true),
    Emoji('🧝‍♀️', 'woman elf', hasSkinTone: true),
    Emoji('🧞', 'genie'),
    Emoji('🧞‍♂️', 'man genie'),
    Emoji('🧞‍♀️', 'woman genie'),
    Emoji('🧟', 'zombie'),
    Emoji('🧟‍♂️', 'man zombie'),
    Emoji('🧟‍♀️', 'woman zombie'),
    Emoji('🧌', 'troll'),
    Emoji('🫈', 'hairy creature'),
    Emoji('💆', 'person getting massage', hasSkinTone: true),
    Emoji('💆‍♂️', 'man getting massage', hasSkinTone: true),
    Emoji('💆‍♀️', 'woman getting massage', hasSkinTone: true),
    Emoji('💇', 'person getting haircut', hasSkinTone: true),
    Emoji('💇‍♂️', 'man getting haircut', hasSkinTone: true),
    Emoji('💇‍♀️', 'woman getting haircut', hasSkinTone: true),
    Emoji('🚶', 'person walking', hasSkinTone: true),
    Emoji('🚶‍♂️', 'man walking', hasSkinTone: true),
    Emoji('🚶‍♀️', 'woman walking', hasSkinTone: true),
    Emoji('🚶‍➡️', 'person walking facing right', hasSkinTone: true),
    Emoji('🚶‍♀️‍➡️', 'woman walking facing right', hasSkinTone: true),
    Emoji('🚶‍♂️‍➡️', 'man walking facing right', hasSkinTone: true),
    Emoji('🧍', 'person standing', hasSkinTone: true),
    Emoji('🧍‍♂️', 'man standing', hasSkinTone: true),
    Emoji('🧍‍♀️', 'woman standing', hasSkinTone: true),
    Emoji('🧎', 'person kneeling', hasSkinTone: true),
    Emoji('🧎‍♂️', 'man kneeling', hasSkinTone: true),
    Emoji('🧎‍♀️', 'woman kneeling', hasSkinTone: true),
    Emoji('🧎‍➡️', 'person kneeling facing right', hasSkinTone: true),
    Emoji('🧎‍♀️‍➡️', 'woman kneeling facing right', hasSkinTone: true),
    Emoji('🧎‍♂️‍➡️', 'man kneeling facing right', hasSkinTone: true),
    Emoji('🧑‍🦯', 'person with white cane', hasSkinTone: true),
    Emoji('🧑‍🦯‍➡️', 'person with white cane facing right', hasSkinTone: true),
    Emoji('👨‍🦯', 'man with white cane', hasSkinTone: true),
    Emoji('👨‍🦯‍➡️', 'man with white cane facing right', hasSkinTone: true),
    Emoji('👩‍🦯', 'woman with white cane', hasSkinTone: true),
    Emoji('👩‍🦯‍➡️', 'woman with white cane facing right', hasSkinTone: true),
    Emoji('🧑‍🦼', 'person in motorized wheelchair', hasSkinTone: true),
    Emoji(
      '🧑‍🦼‍➡️',
      'person in motorized wheelchair facing right',
      hasSkinTone: true,
    ),
    Emoji('👨‍🦼', 'man in motorized wheelchair', hasSkinTone: true),
    Emoji(
      '👨‍🦼‍➡️',
      'man in motorized wheelchair facing right',
      hasSkinTone: true,
    ),
    Emoji('👩‍🦼', 'woman in motorized wheelchair', hasSkinTone: true),
    Emoji(
      '👩‍🦼‍➡️',
      'woman in motorized wheelchair facing right',
      hasSkinTone: true,
    ),
    Emoji('🧑‍🦽', 'person in manual wheelchair', hasSkinTone: true),
    Emoji(
      '🧑‍🦽‍➡️',
      'person in manual wheelchair facing right',
      hasSkinTone: true,
    ),
    Emoji('👨‍🦽', 'man in manual wheelchair', hasSkinTone: true),
    Emoji(
      '👨‍🦽‍➡️',
      'man in manual wheelchair facing right',
      hasSkinTone: true,
    ),
    Emoji('👩‍🦽', 'woman in manual wheelchair', hasSkinTone: true),
    Emoji(
      '👩‍🦽‍➡️',
      'woman in manual wheelchair facing right',
      hasSkinTone: true,
    ),
    Emoji('🏃', 'person running', hasSkinTone: true),
    Emoji('🏃‍♂️', 'man running', hasSkinTone: true),
    Emoji('🏃‍♀️', 'woman running', hasSkinTone: true),
    Emoji('🏃‍➡️', 'person running facing right', hasSkinTone: true),
    Emoji('🏃‍♀️‍➡️', 'woman running facing right', hasSkinTone: true),
    Emoji('🏃‍♂️‍➡️', 'man running facing right', hasSkinTone: true),
    Emoji('🧑‍🩰', 'ballet dancer', hasSkinTone: true),
    Emoji('💃', 'woman dancing', hasSkinTone: true),
    Emoji('🕺', 'man dancing', hasSkinTone: true),
    Emoji('🕴️', 'person in suit levitating'),
    Emoji('👯', 'people with bunny ears', hasSkinTone: true),
    Emoji('👯‍♂️', 'men with bunny ears', hasSkinTone: true),
    Emoji('👯‍♀️', 'women with bunny ears', hasSkinTone: true),
    Emoji('🧖', 'person in steamy room', hasSkinTone: true),
    Emoji('🧖‍♂️', 'man in steamy room', hasSkinTone: true),
    Emoji('🧖‍♀️', 'woman in steamy room', hasSkinTone: true),
    Emoji('🧗', 'person climbing', hasSkinTone: true),
    Emoji('🧗‍♂️', 'man climbing', hasSkinTone: true),
    Emoji('🧗‍♀️', 'woman climbing', hasSkinTone: true),
    Emoji('🤺', 'person fencing'),
    Emoji('🏇', 'horse racing', hasSkinTone: true),
    Emoji('⛷️', 'skier'),
    Emoji('🏂', 'snowboarder', hasSkinTone: true),
    Emoji('🏌️', 'person golfing'),
    Emoji('🏌️‍♂️', 'man golfing'),
    Emoji('🏌️‍♀️', 'woman golfing'),
    Emoji('🏄', 'person surfing', hasSkinTone: true),
    Emoji('🏄‍♂️', 'man surfing', hasSkinTone: true),
    Emoji('🏄‍♀️', 'woman surfing', hasSkinTone: true),
    Emoji('🚣', 'person rowing boat', hasSkinTone: true),
    Emoji('🚣‍♂️', 'man rowing boat', hasSkinTone: true),
    Emoji('🚣‍♀️', 'woman rowing boat', hasSkinTone: true),
    Emoji('🏊', 'person swimming', hasSkinTone: true),
    Emoji('🏊‍♂️', 'man swimming', hasSkinTone: true),
    Emoji('🏊‍♀️', 'woman swimming', hasSkinTone: true),
    Emoji('⛹️', 'person bouncing ball'),
    Emoji('⛹️‍♂️', 'man bouncing ball'),
    Emoji('⛹️‍♀️', 'woman bouncing ball'),
    Emoji('🏋️', 'person lifting weights'),
    Emoji('🏋️‍♂️', 'man lifting weights'),
    Emoji('🏋️‍♀️', 'woman lifting weights'),
    Emoji('🚴', 'person biking', hasSkinTone: true),
    Emoji('🚴‍♂️', 'man biking', hasSkinTone: true),
    Emoji('🚴‍♀️', 'woman biking', hasSkinTone: true),
    Emoji('🚵', 'person mountain biking', hasSkinTone: true),
    Emoji('🚵‍♂️', 'man mountain biking', hasSkinTone: true),
    Emoji('🚵‍♀️', 'woman mountain biking', hasSkinTone: true),
    Emoji('🤸', 'person cartwheeling', hasSkinTone: true),
    Emoji('🤸‍♂️', 'man cartwheeling', hasSkinTone: true),
    Emoji('🤸‍♀️', 'woman cartwheeling', hasSkinTone: true),
    Emoji('🤼', 'people wrestling', hasSkinTone: true),
    Emoji('🤼‍♂️', 'men wrestling', hasSkinTone: true),
    Emoji('🤼‍♀️', 'women wrestling', hasSkinTone: true),
    Emoji('🤽', 'person playing water polo', hasSkinTone: true),
    Emoji('🤽‍♂️', 'man playing water polo', hasSkinTone: true),
    Emoji('🤽‍♀️', 'woman playing water polo', hasSkinTone: true),
    Emoji('🤾', 'person playing handball', hasSkinTone: true),
    Emoji('🤾‍♂️', 'man playing handball', hasSkinTone: true),
    Emoji('🤾‍♀️', 'woman playing handball', hasSkinTone: true),
    Emoji('🤹', 'person juggling', hasSkinTone: true),
    Emoji('🤹‍♂️', 'man juggling', hasSkinTone: true),
    Emoji('🤹‍♀️', 'woman juggling', hasSkinTone: true),
    Emoji('🧘', 'person in lotus position', hasSkinTone: true),
    Emoji('🧘‍♂️', 'man in lotus position', hasSkinTone: true),
    Emoji('🧘‍♀️', 'woman in lotus position', hasSkinTone: true),
    Emoji('🛀', 'person taking bath', hasSkinTone: true),
    Emoji('🛌', 'person in bed', hasSkinTone: true),
    Emoji('🧑‍🤝‍🧑', 'people holding hands', hasSkinTone: true),
    Emoji('👭', 'women holding hands', hasSkinTone: true),
    Emoji('👫', 'woman and man holding hands', hasSkinTone: true),
    Emoji('👬', 'men holding hands', hasSkinTone: true),
    Emoji('💏', 'kiss', hasSkinTone: true),
    Emoji('👩‍❤️‍💋‍👨', 'kiss: woman, man', hasSkinTone: true),
    Emoji('👨‍❤️‍💋‍👨', 'kiss: man, man', hasSkinTone: true),
    Emoji('👩‍❤️‍💋‍👩', 'kiss: woman, woman', hasSkinTone: true),
    Emoji('💑', 'couple with heart', hasSkinTone: true),
    Emoji('👩‍❤️‍👨', 'couple with heart: woman, man', hasSkinTone: true),
    Emoji('👨‍❤️‍👨', 'couple with heart: man, man', hasSkinTone: true),
    Emoji('👩‍❤️‍👩', 'couple with heart: woman, woman', hasSkinTone: true),
    Emoji('👨‍👩‍👦', 'family: man, woman, boy'),
    Emoji('👨‍👩‍👧', 'family: man, woman, girl'),
    Emoji('👨‍👩‍👧‍👦', 'family: man, woman, girl, boy'),
    Emoji('👨‍👩‍👦‍👦', 'family: man, woman, boy, boy'),
    Emoji('👨‍👩‍👧‍👧', 'family: man, woman, girl, girl'),
    Emoji('👨‍👨‍👦', 'family: man, man, boy'),
    Emoji('👨‍👨‍👧', 'family: man, man, girl'),
    Emoji('👨‍👨‍👧‍👦', 'family: man, man, girl, boy'),
    Emoji('👨‍👨‍👦‍👦', 'family: man, man, boy, boy'),
    Emoji('👨‍👨‍👧‍👧', 'family: man, man, girl, girl'),
    Emoji('👩‍👩‍👦', 'family: woman, woman, boy'),
    Emoji('👩‍👩‍👧', 'family: woman, woman, girl'),
    Emoji('👩‍👩‍👧‍👦', 'family: woman, woman, girl, boy'),
    Emoji('👩‍👩‍👦‍👦', 'family: woman, woman, boy, boy'),
    Emoji('👩‍👩‍👧‍👧', 'family: woman, woman, girl, girl'),
    Emoji('👨‍👦', 'family: man, boy'),
    Emoji('👨‍👦‍👦', 'family: man, boy, boy'),
    Emoji('👨‍👧', 'family: man, girl'),
    Emoji('👨‍👧‍👦', 'family: man, girl, boy'),
    Emoji('👨‍👧‍👧', 'family: man, girl, girl'),
    Emoji('👩‍👦', 'family: woman, boy'),
    Emoji('👩‍👦‍👦', 'family: woman, boy, boy'),
    Emoji('👩‍👧', 'family: woman, girl'),
    Emoji('👩‍👧‍👦', 'family: woman, girl, boy'),
    Emoji('👩‍👧‍👧', 'family: woman, girl, girl'),
    Emoji('🗣️', 'speaking head'),
    Emoji('👤', 'bust in silhouette'),
    Emoji('👥', 'busts in silhouette'),
    Emoji('🫂', 'people hugging'),
    Emoji('👪', 'family'),
    Emoji('🧑‍🧑‍🧒', 'family: adult, adult, child'),
    Emoji('🧑‍🧑‍🧒‍🧒', 'family: adult, adult, child, child'),
    Emoji('🧑‍🧒', 'family: adult, child'),
    Emoji('🧑‍🧒‍🧒', 'family: adult, child, child'),
    Emoji('👣', 'footprints'),
    Emoji('🫆', 'fingerprint'),
  ]),
  CategoryEmoji(Category.ANIMALS, [
    Emoji('🐵', 'monkey face'),
    Emoji('🐒', 'monkey'),
    Emoji('🦍', 'gorilla'),
    Emoji('🦧', 'orangutan'),
    Emoji('🐶', 'dog face'),
    Emoji('🐕', 'dog'),
    Emoji('🦮', 'guide dog'),
    Emoji('🐕‍🦺', 'service dog'),
    Emoji('🐩', 'poodle'),
    Emoji('🐺', 'wolf'),
    Emoji('🦊', 'fox'),
    Emoji('🦝', 'raccoon'),
    Emoji('🐱', 'cat face'),
    Emoji('🐈', 'cat'),
    Emoji('🐈‍⬛', 'black cat'),
    Emoji('🦁', 'lion'),
    Emoji('🐯', 'tiger face'),
    Emoji('🐅', 'tiger'),
    Emoji('🐆', 'leopard'),
    Emoji('🐴', 'horse face'),
    Emoji('🫎', 'moose'),
    Emoji('🫏', 'donkey'),
    Emoji('🐎', 'horse'),
    Emoji('🦄', 'unicorn'),
    Emoji('🦓', 'zebra'),
    Emoji('🦌', 'deer'),
    Emoji('🦬', 'bison'),
    Emoji('🐮', 'cow face'),
    Emoji('🐂', 'ox'),
    Emoji('🐃', 'water buffalo'),
    Emoji('🐄', 'cow'),
    Emoji('🐷', 'pig face'),
    Emoji('🐖', 'pig'),
    Emoji('🐗', 'boar'),
    Emoji('🐽', 'pig nose'),
    Emoji('🐏', 'ram'),
    Emoji('🐑', 'ewe'),
    Emoji('🐐', 'goat'),
    Emoji('🐪', 'camel'),
    Emoji('🐫', 'two-hump camel'),
    Emoji('🦙', 'llama'),
    Emoji('🦒', 'giraffe'),
    Emoji('🐘', 'elephant'),
    Emoji('🦣', 'mammoth'),
    Emoji('🦏', 'rhinoceros'),
    Emoji('🦛', 'hippopotamus'),
    Emoji('🐭', 'mouse face'),
    Emoji('🐁', 'mouse'),
    Emoji('🐀', 'rat'),
    Emoji('🐹', 'hamster'),
    Emoji('🐰', 'rabbit face'),
    Emoji('🐇', 'rabbit'),
    Emoji('🐿️', 'chipmunk'),
    Emoji('🦫', 'beaver'),
    Emoji('🦔', 'hedgehog'),
    Emoji('🦇', 'bat'),
    Emoji('🐻', 'bear'),
    Emoji('🐻‍❄️', 'polar bear'),
    Emoji('🐨', 'koala'),
    Emoji('🐼', 'panda'),
    Emoji('🦥', 'sloth'),
    Emoji('🦦', 'otter'),
    Emoji('🦨', 'skunk'),
    Emoji('🦘', 'kangaroo'),
    Emoji('🦡', 'badger'),
    Emoji('🐾', 'paw prints'),
    Emoji('🦃', 'turkey'),
    Emoji('🐔', 'chicken'),
    Emoji('🐓', 'rooster'),
    Emoji('🐣', 'hatching chick'),
    Emoji('🐤', 'baby chick'),
    Emoji('🐥', 'front-facing baby chick'),
    Emoji('🐦', 'bird'),
    Emoji('🐧', 'penguin'),
    Emoji('🕊️', 'dove'),
    Emoji('🦅', 'eagle'),
    Emoji('🦆', 'duck'),
    Emoji('🦢', 'swan'),
    Emoji('🦉', 'owl'),
    Emoji('🦤', 'dodo'),
    Emoji('🪶', 'feather'),
    Emoji('🦩', 'flamingo'),
    Emoji('🦚', 'peacock'),
    Emoji('🦜', 'parrot'),
    Emoji('🪽', 'wing'),
    Emoji('🐦‍⬛', 'black bird'),
    Emoji('🪿', 'goose'),
    Emoji('🐦‍🔥', 'phoenix'),
    Emoji('🐸', 'frog'),
    Emoji('🐊', 'crocodile'),
    Emoji('🐢', 'turtle'),
    Emoji('🦎', 'lizard'),
    Emoji('🐍', 'snake'),
    Emoji('🐲', 'dragon face'),
    Emoji('🐉', 'dragon'),
    Emoji('🦕', 'sauropod'),
    Emoji('🦖', 'T-Rex'),
    Emoji('🐳', 'spouting whale'),
    Emoji('🐋', 'whale'),
    Emoji('🐬', 'dolphin'),
    Emoji('🫍', 'orca'),
    Emoji('🦭', 'seal'),
    Emoji('🐟', 'fish'),
    Emoji('🐠', 'tropical fish'),
    Emoji('🐡', 'blowfish'),
    Emoji('🦈', 'shark'),
    Emoji('🐙', 'octopus'),
    Emoji('🐚', 'spiral shell'),
    Emoji('🪸', 'coral'),
    Emoji('🪼', 'jellyfish'),
    Emoji('🦀', 'crab'),
    Emoji('🦞', 'lobster'),
    Emoji('🦐', 'shrimp'),
    Emoji('🦑', 'squid'),
    Emoji('🦪', 'oyster'),
    Emoji('🐌', 'snail'),
    Emoji('🦋', 'butterfly'),
    Emoji('🐛', 'bug'),
    Emoji('🐜', 'ant'),
    Emoji('🐝', 'honeybee'),
    Emoji('🪲', 'beetle'),
    Emoji('🐞', 'lady beetle'),
    Emoji('🦗', 'cricket'),
    Emoji('🪳', 'cockroach'),
    Emoji('🕷️', 'spider'),
    Emoji('🕸️', 'spider web'),
    Emoji('🦂', 'scorpion'),
    Emoji('🦟', 'mosquito'),
    Emoji('🪰', 'fly'),
    Emoji('🪱', 'worm'),
    Emoji('🦠', 'microbe'),
    Emoji('💐', 'bouquet'),
    Emoji('🌸', 'cherry blossom'),
    Emoji('💮', 'white flower'),
    Emoji('🪷', 'lotus'),
    Emoji('🏵️', 'rosette'),
    Emoji('🌹', 'rose'),
    Emoji('🥀', 'wilted flower'),
    Emoji('🌺', 'hibiscus'),
    Emoji('🌻', 'sunflower'),
    Emoji('🌼', 'blossom'),
    Emoji('🌷', 'tulip'),
    Emoji('🪻', 'hyacinth'),
    Emoji('🌱', 'seedling'),
    Emoji('🪴', 'potted plant'),
    Emoji('🌲', 'evergreen tree'),
    Emoji('🌳', 'deciduous tree'),
    Emoji('🌴', 'palm tree'),
    Emoji('🌵', 'cactus'),
    Emoji('🌾', 'sheaf of rice'),
    Emoji('🌿', 'herb'),
    Emoji('☘️', 'shamrock'),
    Emoji('🍀', 'four leaf clover'),
    Emoji('🍁', 'maple leaf'),
    Emoji('🍂', 'fallen leaf'),
    Emoji('🍃', 'leaf fluttering in wind'),
    Emoji('🪹', 'empty nest'),
    Emoji('🪺', 'nest with eggs'),
    Emoji('🍄', 'mushroom'),
    Emoji('🪾', 'leafless tree'),
  ]),
  CategoryEmoji(Category.FOODS, [
    Emoji('🍇', 'grapes'),
    Emoji('🍈', 'melon'),
    Emoji('🍉', 'watermelon'),
    Emoji('🍊', 'tangerine'),
    Emoji('🍋', 'lemon'),
    Emoji('🍋‍🟩', 'lime'),
    Emoji('🍌', 'banana'),
    Emoji('🍍', 'pineapple'),
    Emoji('🥭', 'mango'),
    Emoji('🍎', 'red apple'),
    Emoji('🍏', 'green apple'),
    Emoji('🍐', 'pear'),
    Emoji('🍑', 'peach'),
    Emoji('🍒', 'cherries'),
    Emoji('🍓', 'strawberry'),
    Emoji('🫐', 'blueberries'),
    Emoji('🥝', 'kiwi fruit'),
    Emoji('🍅', 'tomato'),
    Emoji('🫒', 'olive'),
    Emoji('🥥', 'coconut'),
    Emoji('🥑', 'avocado'),
    Emoji('🍆', 'eggplant'),
    Emoji('🥔', 'potato'),
    Emoji('🥕', 'carrot'),
    Emoji('🌽', 'ear of corn'),
    Emoji('🌶️', 'hot pepper'),
    Emoji('🫑', 'bell pepper'),
    Emoji('🥒', 'cucumber'),
    Emoji('🥬', 'leafy green'),
    Emoji('🥦', 'broccoli'),
    Emoji('🧄', 'garlic'),
    Emoji('🧅', 'onion'),
    Emoji('🥜', 'peanuts'),
    Emoji('🫘', 'beans'),
    Emoji('🌰', 'chestnut'),
    Emoji('🫚', 'ginger root'),
    Emoji('🫛', 'pea pod'),
    Emoji('🍄‍🟫', 'brown mushroom'),
    Emoji('🫜', 'root vegetable'),
    Emoji('🍞', 'bread'),
    Emoji('🥐', 'croissant'),
    Emoji('🥖', 'baguette bread'),
    Emoji('🫓', 'flatbread'),
    Emoji('🥨', 'pretzel'),
    Emoji('🥯', 'bagel'),
    Emoji('🥞', 'pancakes'),
    Emoji('🧇', 'waffle'),
    Emoji('🧀', 'cheese wedge'),
    Emoji('🍖', 'meat on bone'),
    Emoji('🍗', 'poultry leg'),
    Emoji('🥩', 'cut of meat'),
    Emoji('🥓', 'bacon'),
    Emoji('🍔', 'hamburger'),
    Emoji('🍟', 'french fries'),
    Emoji('🍕', 'pizza'),
    Emoji('🌭', 'hot dog'),
    Emoji('🥪', 'sandwich'),
    Emoji('🌮', 'taco'),
    Emoji('🌯', 'burrito'),
    Emoji('🫔', 'tamale'),
    Emoji('🥙', 'stuffed flatbread'),
    Emoji('🧆', 'falafel'),
    Emoji('🥚', 'egg'),
    Emoji('🍳', 'cooking'),
    Emoji('🥘', 'shallow pan of food'),
    Emoji('🍲', 'pot of food'),
    Emoji('🫕', 'fondue'),
    Emoji('🥣', 'bowl with spoon'),
    Emoji('🥗', 'green salad'),
    Emoji('🍿', 'popcorn'),
    Emoji('🧈', 'butter'),
    Emoji('🧂', 'salt'),
    Emoji('🥫', 'canned food'),
    Emoji('🍱', 'bento box'),
    Emoji('🍘', 'rice cracker'),
    Emoji('🍙', 'rice ball'),
    Emoji('🍚', 'cooked rice'),
    Emoji('🍛', 'curry rice'),
    Emoji('🍜', 'steaming bowl'),
    Emoji('🍝', 'spaghetti'),
    Emoji('🍠', 'roasted sweet potato'),
    Emoji('🍢', 'oden'),
    Emoji('🍣', 'sushi'),
    Emoji('🍤', 'fried shrimp'),
    Emoji('🍥', 'fish cake with swirl'),
    Emoji('🥮', 'moon cake'),
    Emoji('🍡', 'dango'),
    Emoji('🥟', 'dumpling'),
    Emoji('🥠', 'fortune cookie'),
    Emoji('🥡', 'takeout box'),
    Emoji('🍦', 'soft ice cream'),
    Emoji('🍧', 'shaved ice'),
    Emoji('🍨', 'ice cream'),
    Emoji('🍩', 'doughnut'),
    Emoji('🍪', 'cookie'),
    Emoji('🎂', 'birthday cake'),
    Emoji('🍰', 'shortcake'),
    Emoji('🧁', 'cupcake'),
    Emoji('🥧', 'pie'),
    Emoji('🍫', 'chocolate bar'),
    Emoji('🍬', 'candy'),
    Emoji('🍭', 'lollipop'),
    Emoji('🍮', 'custard'),
    Emoji('🍯', 'honey pot'),
    Emoji('🍼', 'baby bottle'),
    Emoji('🥛', 'glass of milk'),
    Emoji('☕', 'hot beverage'),
    Emoji('🫖', 'teapot'),
    Emoji('🍵', 'teacup without handle'),
    Emoji('🍶', 'sake'),
    Emoji('🍾', 'bottle with popping cork'),
    Emoji('🍷', 'wine glass'),
    Emoji('🍸', 'cocktail glass'),
    Emoji('🍹', 'tropical drink'),
    Emoji('🍺', 'beer mug'),
    Emoji('🍻', 'clinking beer mugs'),
    Emoji('🥂', 'clinking glasses'),
    Emoji('🥃', 'tumbler glass'),
    Emoji('🫗', 'pouring liquid'),
    Emoji('🥤', 'cup with straw'),
    Emoji('🧋', 'bubble tea'),
    Emoji('🧃', 'beverage box'),
    Emoji('🧉', 'mate'),
    Emoji('🧊', 'ice'),
    Emoji('🥢', 'chopsticks'),
    Emoji('🍽️', 'fork and knife with plate'),
    Emoji('🍴', 'fork and knife'),
    Emoji('🥄', 'spoon'),
    Emoji('🔪', 'kitchen knife'),
    Emoji('🫙', 'jar'),
    Emoji('🏺', 'amphora'),
  ]),
  CategoryEmoji(Category.ACTIVITIES, [
    Emoji('🎃', 'jack-o-lantern'),
    Emoji('🎄', 'Christmas tree'),
    Emoji('🎆', 'fireworks'),
    Emoji('🎇', 'sparkler'),
    Emoji('🧨', 'firecracker'),
    Emoji('✨', 'sparkles'),
    Emoji('🎈', 'balloon'),
    Emoji('🎉', 'party popper'),
    Emoji('🎊', 'confetti ball'),
    Emoji('🎋', 'tanabata tree'),
    Emoji('🎍', 'pine decoration'),
    Emoji('🎎', 'Japanese dolls'),
    Emoji('🎏', 'carp streamer'),
    Emoji('🎐', 'wind chime'),
    Emoji('🎑', 'moon viewing ceremony'),
    Emoji('🧧', 'red envelope'),
    Emoji('🎀', 'ribbon'),
    Emoji('🎁', 'wrapped gift'),
    Emoji('🎗️', 'reminder ribbon'),
    Emoji('🎟️', 'admission tickets'),
    Emoji('🎫', 'ticket'),
    Emoji('🎖️', 'military medal'),
    Emoji('🏆', 'trophy'),
    Emoji('🏅', 'sports medal'),
    Emoji('🥇', '1st place medal'),
    Emoji('🥈', '2nd place medal'),
    Emoji('🥉', '3rd place medal'),
    Emoji('⚽', 'soccer ball'),
    Emoji('⚾', 'baseball'),
    Emoji('🥎', 'softball'),
    Emoji('🏀', 'basketball'),
    Emoji('🏐', 'volleyball'),
    Emoji('🏈', 'american football'),
    Emoji('🏉', 'rugby football'),
    Emoji('🎾', 'tennis'),
    Emoji('🥏', 'flying disc'),
    Emoji('🎳', 'bowling'),
    Emoji('🏏', 'cricket game'),
    Emoji('🏑', 'field hockey'),
    Emoji('🏒', 'ice hockey'),
    Emoji('🥍', 'lacrosse'),
    Emoji('🏓', 'ping pong'),
    Emoji('🏸', 'badminton'),
    Emoji('🥊', 'boxing glove'),
    Emoji('🥋', 'martial arts uniform'),
    Emoji('🥅', 'goal net'),
    Emoji('⛳', 'flag in hole'),
    Emoji('⛸️', 'ice skate'),
    Emoji('🎣', 'fishing pole'),
    Emoji('🤿', 'diving mask'),
    Emoji('🎽', 'running shirt'),
    Emoji('🎿', 'skis'),
    Emoji('🛷', 'sled'),
    Emoji('🥌', 'curling stone'),
    Emoji('🎯', 'bullseye'),
    Emoji('🪀', 'yo-yo'),
    Emoji('🪁', 'kite'),
    Emoji('🔫', 'water pistol'),
    Emoji('🎱', 'pool 8 ball'),
    Emoji('🔮', 'crystal ball'),
    Emoji('🪄', 'magic wand'),
    Emoji('🎮', 'video game'),
    Emoji('🕹️', 'joystick'),
    Emoji('🎰', 'slot machine'),
    Emoji('🎲', 'game die'),
    Emoji('🧩', 'puzzle piece'),
    Emoji('🧸', 'teddy bear'),
    Emoji('🪅', 'piñata'),
    Emoji('🪩', 'mirror ball'),
    Emoji('🪆', 'nesting dolls'),
    Emoji('♠️', 'spade suit'),
    Emoji('♥️', 'heart suit'),
    Emoji('♦️', 'diamond suit'),
    Emoji('♣️', 'club suit'),
    Emoji('♟️', 'chess pawn'),
    Emoji('🃏', 'joker'),
    Emoji('🀄', 'mahjong red dragon'),
    Emoji('🎴', 'flower playing cards'),
    Emoji('🎭', 'performing arts'),
    Emoji('🖼️', 'framed picture'),
    Emoji('🎨', 'artist palette'),
    Emoji('🧵', 'thread'),
    Emoji('🪡', 'sewing needle'),
    Emoji('🧶', 'yarn'),
    Emoji('🪢', 'knot'),
  ]),
  CategoryEmoji(Category.TRAVEL, [
    Emoji('🌍', 'globe showing Europe-Africa'),
    Emoji('🌎', 'globe showing Americas'),
    Emoji('🌏', 'globe showing Asia-Australia'),
    Emoji('🌐', 'globe with meridians'),
    Emoji('🗺️', 'world map'),
    Emoji('🗾', 'map of Japan'),
    Emoji('🧭', 'compass'),
    Emoji('🏔️', 'snow-capped mountain'),
    Emoji('⛰️', 'mountain'),
    Emoji('🛘', 'landslide'),
    Emoji('🌋', 'volcano'),
    Emoji('🗻', 'mount fuji'),
    Emoji('🏕️', 'camping'),
    Emoji('🏖️', 'beach with umbrella'),
    Emoji('🏜️', 'desert'),
    Emoji('🏝️', 'desert island'),
    Emoji('🏞️', 'national park'),
    Emoji('🏟️', 'stadium'),
    Emoji('🏛️', 'classical building'),
    Emoji('🏗️', 'building construction'),
    Emoji('🧱', 'brick'),
    Emoji('🪨', 'rock'),
    Emoji('🪵', 'wood'),
    Emoji('🛖', 'hut'),
    Emoji('🏘️', 'houses'),
    Emoji('🏚️', 'derelict house'),
    Emoji('🏠', 'house'),
    Emoji('🏡', 'house with garden'),
    Emoji('🏢', 'office building'),
    Emoji('🏣', 'Japanese post office'),
    Emoji('🏤', 'post office'),
    Emoji('🏥', 'hospital'),
    Emoji('🏦', 'bank'),
    Emoji('🏨', 'hotel'),
    Emoji('🏩', 'love hotel'),
    Emoji('🏪', 'convenience store'),
    Emoji('🏫', 'school'),
    Emoji('🏬', 'department store'),
    Emoji('🏭', 'factory'),
    Emoji('🏯', 'Japanese castle'),
    Emoji('🏰', 'castle'),
    Emoji('💒', 'wedding'),
    Emoji('🗼', 'Tokyo tower'),
    Emoji('🗽', 'Statue of Liberty'),
    Emoji('⛪', 'church'),
    Emoji('🕌', 'mosque'),
    Emoji('🛕', 'hindu temple'),
    Emoji('🕍', 'synagogue'),
    Emoji('⛩️', 'shinto shrine'),
    Emoji('🕋', 'kaaba'),
    Emoji('⛲', 'fountain'),
    Emoji('⛺', 'tent'),
    Emoji('🌁', 'foggy'),
    Emoji('🌃', 'night with stars'),
    Emoji('🏙️', 'cityscape'),
    Emoji('🌄', 'sunrise over mountains'),
    Emoji('🌅', 'sunrise'),
    Emoji('🌆', 'cityscape at dusk'),
    Emoji('🌇', 'sunset'),
    Emoji('🌉', 'bridge at night'),
    Emoji('♨️', 'hot springs'),
    Emoji('🎠', 'carousel horse'),
    Emoji('🛝', 'playground slide'),
    Emoji('🎡', 'ferris wheel'),
    Emoji('🎢', 'roller coaster'),
    Emoji('💈', 'barber pole'),
    Emoji('🎪', 'circus tent'),
    Emoji('🚂', 'locomotive'),
    Emoji('🚃', 'railway car'),
    Emoji('🚄', 'high-speed train'),
    Emoji('🚅', 'bullet train'),
    Emoji('🚆', 'train'),
    Emoji('🚇', 'metro'),
    Emoji('🚈', 'light rail'),
    Emoji('🚉', 'station'),
    Emoji('🚊', 'tram'),
    Emoji('🚝', 'monorail'),
    Emoji('🚞', 'mountain railway'),
    Emoji('🚋', 'tram car'),
    Emoji('🚌', 'bus'),
    Emoji('🚍', 'oncoming bus'),
    Emoji('🚎', 'trolleybus'),
    Emoji('🚐', 'minibus'),
    Emoji('🚑', 'ambulance'),
    Emoji('🚒', 'fire engine'),
    Emoji('🚓', 'police car'),
    Emoji('🚔', 'oncoming police car'),
    Emoji('🚕', 'taxi'),
    Emoji('🚖', 'oncoming taxi'),
    Emoji('🚗', 'automobile'),
    Emoji('🚘', 'oncoming automobile'),
    Emoji('🚙', 'sport utility vehicle'),
    Emoji('🛻', 'pickup truck'),
    Emoji('🚚', 'delivery truck'),
    Emoji('🚛', 'articulated lorry'),
    Emoji('🚜', 'tractor'),
    Emoji('🏎️', 'racing car'),
    Emoji('🏍️', 'motorcycle'),
    Emoji('🛵', 'motor scooter'),
    Emoji('🦽', 'manual wheelchair'),
    Emoji('🦼', 'motorized wheelchair'),
    Emoji('🛺', 'auto rickshaw'),
    Emoji('🚲', 'bicycle'),
    Emoji('🛴', 'kick scooter'),
    Emoji('🛹', 'skateboard'),
    Emoji('🛼', 'roller skate'),
    Emoji('🚏', 'bus stop'),
    Emoji('🛣️', 'motorway'),
    Emoji('🛤️', 'railway track'),
    Emoji('🛢️', 'oil drum'),
    Emoji('⛽', 'fuel pump'),
    Emoji('🛞', 'wheel'),
    Emoji('🚨', 'police car light'),
    Emoji('🚥', 'horizontal traffic light'),
    Emoji('🚦', 'vertical traffic light'),
    Emoji('🛑', 'stop sign'),
    Emoji('🚧', 'construction'),
    Emoji('⚓', 'anchor'),
    Emoji('🛟', 'ring buoy'),
    Emoji('⛵', 'sailboat'),
    Emoji('🛶', 'canoe'),
    Emoji('🚤', 'speedboat'),
    Emoji('🛳️', 'passenger ship'),
    Emoji('⛴️', 'ferry'),
    Emoji('🛥️', 'motor boat'),
    Emoji('🚢', 'ship'),
    Emoji('✈️', 'airplane'),
    Emoji('🛩️', 'small airplane'),
    Emoji('🛫', 'airplane departure'),
    Emoji('🛬', 'airplane arrival'),
    Emoji('🪂', 'parachute'),
    Emoji('💺', 'seat'),
    Emoji('🚁', 'helicopter'),
    Emoji('🚟', 'suspension railway'),
    Emoji('🚠', 'mountain cableway'),
    Emoji('🚡', 'aerial tramway'),
    Emoji('🛰️', 'satellite'),
    Emoji('🚀', 'rocket'),
    Emoji('🛸', 'flying saucer'),
    Emoji('🛎️', 'bellhop bell'),
    Emoji('🧳', 'luggage'),
    Emoji('⌛', 'hourglass done'),
    Emoji('⏳', 'hourglass not done'),
    Emoji('⌚', 'watch'),
    Emoji('⏰', 'alarm clock'),
    Emoji('⏱️', 'stopwatch'),
    Emoji('⏲️', 'timer clock'),
    Emoji('🕰️', 'mantelpiece clock'),
    Emoji('🕛', 'twelve o’clock'),
    Emoji('🕧', 'twelve-thirty'),
    Emoji('🕐', 'one o’clock'),
    Emoji('🕜', 'one-thirty'),
    Emoji('🕑', 'two o’clock'),
    Emoji('🕝', 'two-thirty'),
    Emoji('🕒', 'three o’clock'),
    Emoji('🕞', 'three-thirty'),
    Emoji('🕓', 'four o’clock'),
    Emoji('🕟', 'four-thirty'),
    Emoji('🕔', 'five o’clock'),
    Emoji('🕠', 'five-thirty'),
    Emoji('🕕', 'six o’clock'),
    Emoji('🕡', 'six-thirty'),
    Emoji('🕖', 'seven o’clock'),
    Emoji('🕢', 'seven-thirty'),
    Emoji('🕗', 'eight o’clock'),
    Emoji('🕣', 'eight-thirty'),
    Emoji('🕘', 'nine o’clock'),
    Emoji('🕤', 'nine-thirty'),
    Emoji('🕙', 'ten o’clock'),
    Emoji('🕥', 'ten-thirty'),
    Emoji('🕚', 'eleven o’clock'),
    Emoji('🕦', 'eleven-thirty'),
    Emoji('🌑', 'new moon'),
    Emoji('🌒', 'waxing crescent moon'),
    Emoji('🌓', 'first quarter moon'),
    Emoji('🌔', 'waxing gibbous moon'),
    Emoji('🌕', 'full moon'),
    Emoji('🌖', 'waning gibbous moon'),
    Emoji('🌗', 'last quarter moon'),
    Emoji('🌘', 'waning crescent moon'),
    Emoji('🌙', 'crescent moon'),
    Emoji('🌚', 'new moon face'),
    Emoji('🌛', 'first quarter moon face'),
    Emoji('🌜', 'last quarter moon face'),
    Emoji('🌡️', 'thermometer'),
    Emoji('☀️', 'sun'),
    Emoji('🌝', 'full moon face'),
    Emoji('🌞', 'sun with face'),
    Emoji('🪐', 'ringed planet'),
    Emoji('⭐', 'star'),
    Emoji('🌟', 'glowing star'),
    Emoji('🌠', 'shooting star'),
    Emoji('🌌', 'milky way'),
    Emoji('☁️', 'cloud'),
    Emoji('⛅', 'sun behind cloud'),
    Emoji('⛈️', 'cloud with lightning and rain'),
    Emoji('🌤️', 'sun behind small cloud'),
    Emoji('🌥️', 'sun behind large cloud'),
    Emoji('🌦️', 'sun behind rain cloud'),
    Emoji('🌧️', 'cloud with rain'),
    Emoji('🌨️', 'cloud with snow'),
    Emoji('🌩️', 'cloud with lightning'),
    Emoji('🌪️', 'tornado'),
    Emoji('🌫️', 'fog'),
    Emoji('🌬️', 'wind face'),
    Emoji('🌀', 'cyclone'),
    Emoji('🌈', 'rainbow'),
    Emoji('🌂', 'closed umbrella'),
    Emoji('☂️', 'umbrella'),
    Emoji('☔', 'umbrella with rain drops'),
    Emoji('⛱️', 'umbrella on ground'),
    Emoji('⚡', 'high voltage'),
    Emoji('❄️', 'snowflake'),
    Emoji('☃️', 'snowman'),
    Emoji('⛄', 'snowman without snow'),
    Emoji('☄️', 'comet'),
    Emoji('🔥', 'fire'),
    Emoji('💧', 'droplet'),
    Emoji('🌊', 'water wave'),
  ]),
  CategoryEmoji(Category.OBJECTS, [
    Emoji('👓', 'glasses'),
    Emoji('🕶️', 'sunglasses'),
    Emoji('🥽', 'goggles'),
    Emoji('🥼', 'lab coat'),
    Emoji('🦺', 'safety vest'),
    Emoji('👔', 'necktie'),
    Emoji('👕', 't-shirt'),
    Emoji('👖', 'jeans'),
    Emoji('🧣', 'scarf'),
    Emoji('🧤', 'gloves'),
    Emoji('🧥', 'coat'),
    Emoji('🧦', 'socks'),
    Emoji('👗', 'dress'),
    Emoji('👘', 'kimono'),
    Emoji('🥻', 'sari'),
    Emoji('🩱', 'one-piece swimsuit'),
    Emoji('🩲', 'briefs'),
    Emoji('🩳', 'shorts'),
    Emoji('👙', 'bikini'),
    Emoji('👚', 'woman’s clothes'),
    Emoji('🪭', 'folding hand fan'),
    Emoji('👛', 'purse'),
    Emoji('👜', 'handbag'),
    Emoji('👝', 'clutch bag'),
    Emoji('🛍️', 'shopping bags'),
    Emoji('🎒', 'backpack'),
    Emoji('🩴', 'thong sandal'),
    Emoji('👞', 'man’s shoe'),
    Emoji('👟', 'running shoe'),
    Emoji('🥾', 'hiking boot'),
    Emoji('🥿', 'flat shoe'),
    Emoji('👠', 'high-heeled shoe'),
    Emoji('👡', 'woman’s sandal'),
    Emoji('🩰', 'ballet shoes'),
    Emoji('👢', 'woman’s boot'),
    Emoji('🪮', 'hair pick'),
    Emoji('👑', 'crown'),
    Emoji('👒', 'woman’s hat'),
    Emoji('🎩', 'top hat'),
    Emoji('🎓', 'graduation cap'),
    Emoji('🧢', 'billed cap'),
    Emoji('🪖', 'military helmet'),
    Emoji('⛑️', 'rescue worker’s helmet'),
    Emoji('📿', 'prayer beads'),
    Emoji('💄', 'lipstick'),
    Emoji('💍', 'ring'),
    Emoji('💎', 'gem stone'),
    Emoji('🔇', 'muted speaker'),
    Emoji('🔈', 'speaker low volume'),
    Emoji('🔉', 'speaker medium volume'),
    Emoji('🔊', 'speaker high volume'),
    Emoji('📢', 'loudspeaker'),
    Emoji('📣', 'megaphone'),
    Emoji('📯', 'postal horn'),
    Emoji('🔔', 'bell'),
    Emoji('🔕', 'bell with slash'),
    Emoji('🎼', 'musical score'),
    Emoji('🎵', 'musical note'),
    Emoji('🎶', 'musical notes'),
    Emoji('🎙️', 'studio microphone'),
    Emoji('🎚️', 'level slider'),
    Emoji('🎛️', 'control knobs'),
    Emoji('🎤', 'microphone'),
    Emoji('🎧', 'headphone'),
    Emoji('📻', 'radio'),
    Emoji('🎷', 'saxophone'),
    Emoji('🎺', 'trumpet'),
    Emoji('🪊', 'trombone'),
    Emoji('🪗', 'accordion'),
    Emoji('🎸', 'guitar'),
    Emoji('🎹', 'musical keyboard'),
    Emoji('🎻', 'violin'),
    Emoji('🪕', 'banjo'),
    Emoji('🥁', 'drum'),
    Emoji('🪘', 'long drum'),
    Emoji('🪇', 'maracas'),
    Emoji('🪈', 'flute'),
    Emoji('🪉', 'harp'),
    Emoji('📱', 'mobile phone'),
    Emoji('📲', 'mobile phone with arrow'),
    Emoji('☎️', 'telephone'),
    Emoji('📞', 'telephone receiver'),
    Emoji('📟', 'pager'),
    Emoji('📠', 'fax machine'),
    Emoji('🔋', 'battery'),
    Emoji('🪫', 'low battery'),
    Emoji('🔌', 'electric plug'),
    Emoji('💻', 'laptop'),
    Emoji('🖥️', 'desktop computer'),
    Emoji('🖨️', 'printer'),
    Emoji('⌨️', 'keyboard'),
    Emoji('🖱️', 'computer mouse'),
    Emoji('🖲️', 'trackball'),
    Emoji('💽', 'computer disk'),
    Emoji('💾', 'floppy disk'),
    Emoji('💿', 'optical disk'),
    Emoji('📀', 'dvd'),
    Emoji('🧮', 'abacus'),
    Emoji('🎥', 'movie camera'),
    Emoji('🎞️', 'film frames'),
    Emoji('📽️', 'film projector'),
    Emoji('🎬', 'clapper board'),
    Emoji('📺', 'television'),
    Emoji('📷', 'camera'),
    Emoji('📸', 'camera with flash'),
    Emoji('📹', 'video camera'),
    Emoji('📼', 'videocassette'),
    Emoji('🔍', 'magnifying glass tilted left'),
    Emoji('🔎', 'magnifying glass tilted right'),
    Emoji('🕯️', 'candle'),
    Emoji('💡', 'light bulb'),
    Emoji('🔦', 'flashlight'),
    Emoji('🏮', 'red paper lantern'),
    Emoji('🪔', 'diya lamp'),
    Emoji('📔', 'notebook with decorative cover'),
    Emoji('📕', 'closed book'),
    Emoji('📖', 'open book'),
    Emoji('📗', 'green book'),
    Emoji('📘', 'blue book'),
    Emoji('📙', 'orange book'),
    Emoji('📚', 'books'),
    Emoji('📓', 'notebook'),
    Emoji('📒', 'ledger'),
    Emoji('📃', 'page with curl'),
    Emoji('📜', 'scroll'),
    Emoji('📄', 'page facing up'),
    Emoji('📰', 'newspaper'),
    Emoji('🗞️', 'rolled-up newspaper'),
    Emoji('📑', 'bookmark tabs'),
    Emoji('🔖', 'bookmark'),
    Emoji('🏷️', 'label'),
    Emoji('🪙', 'coin'),
    Emoji('💰', 'money bag'),
    Emoji('🪎', 'treasure chest'),
    Emoji('💴', 'yen banknote'),
    Emoji('💵', 'dollar banknote'),
    Emoji('💶', 'euro banknote'),
    Emoji('💷', 'pound banknote'),
    Emoji('💸', 'money with wings'),
    Emoji('💳', 'credit card'),
    Emoji('🧾', 'receipt'),
    Emoji('💹', 'chart increasing with yen'),
    Emoji('✉️', 'envelope'),
    Emoji('📧', 'e-mail'),
    Emoji('📨', 'incoming envelope'),
    Emoji('📩', 'envelope with arrow'),
    Emoji('📤', 'outbox tray'),
    Emoji('📥', 'inbox tray'),
    Emoji('📦', 'package'),
    Emoji('📫', 'closed mailbox with raised flag'),
    Emoji('📪', 'closed mailbox with lowered flag'),
    Emoji('📬', 'open mailbox with raised flag'),
    Emoji('📭', 'open mailbox with lowered flag'),
    Emoji('📮', 'postbox'),
    Emoji('🗳️', 'ballot box with ballot'),
    Emoji('✏️', 'pencil'),
    Emoji('✒️', 'black nib'),
    Emoji('🖋️', 'fountain pen'),
    Emoji('🖊️', 'pen'),
    Emoji('🖌️', 'paintbrush'),
    Emoji('🖍️', 'crayon'),
    Emoji('📝', 'memo'),
    Emoji('💼', 'briefcase'),
    Emoji('📁', 'file folder'),
    Emoji('📂', 'open file folder'),
    Emoji('🗂️', 'card index dividers'),
    Emoji('📅', 'calendar'),
    Emoji('📆', 'tear-off calendar'),
    Emoji('🗒️', 'spiral notepad'),
    Emoji('🗓️', 'spiral calendar'),
    Emoji('📇', 'card index'),
    Emoji('📈', 'chart increasing'),
    Emoji('📉', 'chart decreasing'),
    Emoji('📊', 'bar chart'),
    Emoji('📋', 'clipboard'),
    Emoji('📌', 'pushpin'),
    Emoji('📍', 'round pushpin'),
    Emoji('📎', 'paperclip'),
    Emoji('🖇️', 'linked paperclips'),
    Emoji('📏', 'straight ruler'),
    Emoji('📐', 'triangular ruler'),
    Emoji('✂️', 'scissors'),
    Emoji('🗃️', 'card file box'),
    Emoji('🗄️', 'file cabinet'),
    Emoji('🗑️', 'wastebasket'),
    Emoji('🔒', 'locked'),
    Emoji('🔓', 'unlocked'),
    Emoji('🔏', 'locked with pen'),
    Emoji('🔐', 'locked with key'),
    Emoji('🔑', 'key'),
    Emoji('🗝️', 'old key'),
    Emoji('🔨', 'hammer'),
    Emoji('🪓', 'axe'),
    Emoji('⛏️', 'pick'),
    Emoji('⚒️', 'hammer and pick'),
    Emoji('🛠️', 'hammer and wrench'),
    Emoji('🗡️', 'dagger'),
    Emoji('⚔️', 'crossed swords'),
    Emoji('💣', 'bomb'),
    Emoji('🪃', 'boomerang'),
    Emoji('🏹', 'bow and arrow'),
    Emoji('🛡️', 'shield'),
    Emoji('🪚', 'carpentry saw'),
    Emoji('🔧', 'wrench'),
    Emoji('🪛', 'screwdriver'),
    Emoji('🔩', 'nut and bolt'),
    Emoji('⚙️', 'gear'),
    Emoji('🗜️', 'clamp'),
    Emoji('⚖️', 'balance scale'),
    Emoji('🦯', 'white cane'),
    Emoji('🔗', 'link'),
    Emoji('⛓️‍💥', 'broken chain'),
    Emoji('⛓️', 'chains'),
    Emoji('🪝', 'hook'),
    Emoji('🧰', 'toolbox'),
    Emoji('🧲', 'magnet'),
    Emoji('🪜', 'ladder'),
    Emoji('🪏', 'shovel'),
    Emoji('⚗️', 'alembic'),
    Emoji('🧪', 'test tube'),
    Emoji('🧫', 'petri dish'),
    Emoji('🧬', 'dna'),
    Emoji('🔬', 'microscope'),
    Emoji('🔭', 'telescope'),
    Emoji('📡', 'satellite antenna'),
    Emoji('💉', 'syringe'),
    Emoji('🩸', 'drop of blood'),
    Emoji('💊', 'pill'),
    Emoji('🩹', 'adhesive bandage'),
    Emoji('🩼', 'crutch'),
    Emoji('🩺', 'stethoscope'),
    Emoji('🩻', 'x-ray'),
    Emoji('🚪', 'door'),
    Emoji('🛗', 'elevator'),
    Emoji('🪞', 'mirror'),
    Emoji('🪟', 'window'),
    Emoji('🛏️', 'bed'),
    Emoji('🛋️', 'couch and lamp'),
    Emoji('🪑', 'chair'),
    Emoji('🚽', 'toilet'),
    Emoji('🪠', 'plunger'),
    Emoji('🚿', 'shower'),
    Emoji('🛁', 'bathtub'),
    Emoji('🪤', 'mouse trap'),
    Emoji('🪒', 'razor'),
    Emoji('🧴', 'lotion bottle'),
    Emoji('🧷', 'safety pin'),
    Emoji('🧹', 'broom'),
    Emoji('🧺', 'basket'),
    Emoji('🧻', 'roll of paper'),
    Emoji('🪣', 'bucket'),
    Emoji('🧼', 'soap'),
    Emoji('🫧', 'bubbles'),
    Emoji('🪥', 'toothbrush'),
    Emoji('🧽', 'sponge'),
    Emoji('🧯', 'fire extinguisher'),
    Emoji('🛒', 'shopping cart'),
    Emoji('🚬', 'cigarette'),
    Emoji('⚰️', 'coffin'),
    Emoji('🪦', 'headstone'),
    Emoji('⚱️', 'funeral urn'),
    Emoji('🧿', 'nazar amulet'),
    Emoji('🪬', 'hamsa'),
    Emoji('🗿', 'moai'),
    Emoji('🪧', 'placard'),
    Emoji('🪪', 'identification card'),
  ]),
  CategoryEmoji(Category.SYMBOLS, [
    Emoji('🏧', 'ATM sign'),
    Emoji('🚮', 'litter in bin sign'),
    Emoji('🚰', 'potable water'),
    Emoji('♿', 'wheelchair symbol'),
    Emoji('🚹', 'men’s room'),
    Emoji('🚺', 'women’s room'),
    Emoji('🚻', 'restroom'),
    Emoji('🚼', 'baby symbol'),
    Emoji('🚾', 'water closet'),
    Emoji('🛂', 'passport control'),
    Emoji('🛃', 'customs'),
    Emoji('🛄', 'baggage claim'),
    Emoji('🛅', 'left luggage'),
    Emoji('⚠️', 'warning'),
    Emoji('🚸', 'children crossing'),
    Emoji('⛔', 'no entry'),
    Emoji('🚫', 'prohibited'),
    Emoji('🚳', 'no bicycles'),
    Emoji('🚭', 'no smoking'),
    Emoji('🚯', 'no littering'),
    Emoji('🚱', 'non-potable water'),
    Emoji('🚷', 'no pedestrians'),
    Emoji('📵', 'no mobile phones'),
    Emoji('🔞', 'no one under eighteen'),
    Emoji('☢️', 'radioactive'),
    Emoji('☣️', 'biohazard'),
    Emoji('⬆️', 'up arrow'),
    Emoji('↗️', 'up-right arrow'),
    Emoji('➡️', 'right arrow'),
    Emoji('↘️', 'down-right arrow'),
    Emoji('⬇️', 'down arrow'),
    Emoji('↙️', 'down-left arrow'),
    Emoji('⬅️', 'left arrow'),
    Emoji('↖️', 'up-left arrow'),
    Emoji('↕️', 'up-down arrow'),
    Emoji('↔️', 'left-right arrow'),
    Emoji('↩️', 'right arrow curving left'),
    Emoji('↪️', 'left arrow curving right'),
    Emoji('⤴️', 'right arrow curving up'),
    Emoji('⤵️', 'right arrow curving down'),
    Emoji('🔃', 'clockwise vertical arrows'),
    Emoji('🔄', 'counterclockwise arrows button'),
    Emoji('🔙', 'BACK arrow'),
    Emoji('🔚', 'END arrow'),
    Emoji('🔛', 'ON! arrow'),
    Emoji('🔜', 'SOON arrow'),
    Emoji('🔝', 'TOP arrow'),
    Emoji('🛐', 'place of worship'),
    Emoji('⚛️', 'atom symbol'),
    Emoji('🕉️', 'om'),
    Emoji('✡️', 'star of David'),
    Emoji('☸️', 'wheel of dharma'),
    Emoji('☯️', 'yin yang'),
    Emoji('✝️', 'latin cross'),
    Emoji('☦️', 'orthodox cross'),
    Emoji('☪️', 'star and crescent'),
    Emoji('☮️', 'peace symbol'),
    Emoji('🕎', 'menorah'),
    Emoji('🔯', 'dotted six-pointed star'),
    Emoji('🪯', 'khanda'),
    Emoji('♈', 'Aries'),
    Emoji('♉', 'Taurus'),
    Emoji('♊', 'Gemini'),
    Emoji('♋', 'Cancer'),
    Emoji('♌', 'Leo'),
    Emoji('♍', 'Virgo'),
    Emoji('♎', 'Libra'),
    Emoji('♏', 'Scorpio'),
    Emoji('♐', 'Sagittarius'),
    Emoji('♑', 'Capricorn'),
    Emoji('♒', 'Aquarius'),
    Emoji('♓', 'Pisces'),
    Emoji('⛎', 'Ophiuchus'),
    Emoji('🔀', 'shuffle tracks button'),
    Emoji('🔁', 'repeat button'),
    Emoji('🔂', 'repeat single button'),
    Emoji('▶️', 'play button'),
    Emoji('⏩', 'fast-forward button'),
    Emoji('⏭️', 'next track button'),
    Emoji('⏯️', 'play or pause button'),
    Emoji('◀️', 'reverse button'),
    Emoji('⏪', 'fast reverse button'),
    Emoji('⏮️', 'last track button'),
    Emoji('🔼', 'upwards button'),
    Emoji('⏫', 'fast up button'),
    Emoji('🔽', 'downwards button'),
    Emoji('⏬', 'fast down button'),
    Emoji('⏸️', 'pause button'),
    Emoji('⏹️', 'stop button'),
    Emoji('⏺️', 'record button'),
    Emoji('⏏️', 'eject button'),
    Emoji('🎦', 'cinema'),
    Emoji('🔅', 'dim button'),
    Emoji('🔆', 'bright button'),
    Emoji('📶', 'antenna bars'),
    Emoji('🛜', 'wireless'),
    Emoji('📳', 'vibration mode'),
    Emoji('📴', 'mobile phone off'),
    Emoji('♀️', 'female sign'),
    Emoji('♂️', 'male sign'),
    Emoji('⚧️', 'transgender symbol'),
    Emoji('✖️', 'multiply'),
    Emoji('➕', 'plus'),
    Emoji('➖', 'minus'),
    Emoji('➗', 'divide'),
    Emoji('🟰', 'heavy equals sign'),
    Emoji('♾️', 'infinity'),
    Emoji('‼️', 'double exclamation mark'),
    Emoji('⁉️', 'exclamation question mark'),
    Emoji('❓', 'red question mark'),
    Emoji('❔', 'white question mark'),
    Emoji('❕', 'white exclamation mark'),
    Emoji('❗', 'red exclamation mark'),
    Emoji('〰️', 'wavy dash'),
    Emoji('💱', 'currency exchange'),
    Emoji('💲', 'heavy dollar sign'),
    Emoji('⚕️', 'medical symbol'),
    Emoji('♻️', 'recycling symbol'),
    Emoji('⚜️', 'fleur-de-lis'),
    Emoji('🔱', 'trident emblem'),
    Emoji('📛', 'name badge'),
    Emoji('🔰', 'Japanese symbol for beginner'),
    Emoji('⭕', 'hollow red circle'),
    Emoji('✅', 'check mark button'),
    Emoji('☑️', 'check box with check'),
    Emoji('✔️', 'check mark'),
    Emoji('❌', 'cross mark'),
    Emoji('❎', 'cross mark button'),
    Emoji('➰', 'curly loop'),
    Emoji('➿', 'double curly loop'),
    Emoji('〽️', 'part alternation mark'),
    Emoji('✳️', 'eight-spoked asterisk'),
    Emoji('✴️', 'eight-pointed star'),
    Emoji('❇️', 'sparkle'),
    Emoji('©️', 'copyright'),
    Emoji('®️', 'registered'),
    Emoji('™️', 'trade mark'),
    Emoji('🫟', 'splatter'),
    Emoji('#️⃣', 'keycap: #'),
    Emoji('*️⃣', 'keycap: *'),
    Emoji('0️⃣', 'keycap: 0'),
    Emoji('1️⃣', 'keycap: 1'),
    Emoji('2️⃣', 'keycap: 2'),
    Emoji('3️⃣', 'keycap: 3'),
    Emoji('4️⃣', 'keycap: 4'),
    Emoji('5️⃣', 'keycap: 5'),
    Emoji('6️⃣', 'keycap: 6'),
    Emoji('7️⃣', 'keycap: 7'),
    Emoji('8️⃣', 'keycap: 8'),
    Emoji('9️⃣', 'keycap: 9'),
    Emoji('🔟', 'keycap: 10'),
    Emoji('🔠', 'input latin uppercase'),
    Emoji('🔡', 'input latin lowercase'),
    Emoji('🔢', 'input numbers'),
    Emoji('🔣', 'input symbols'),
    Emoji('🔤', 'input latin letters'),
    Emoji('🅰️', 'A button (blood type)'),
    Emoji('🆎', 'AB button (blood type)'),
    Emoji('🅱️', 'B button (blood type)'),
    Emoji('🆑', 'CL button'),
    Emoji('🆒', 'COOL button'),
    Emoji('🆓', 'FREE button'),
    Emoji('ℹ️', 'information'),
    Emoji('🆔', 'ID button'),
    Emoji('Ⓜ️', 'circled M'),
    Emoji('🆕', 'NEW button'),
    Emoji('🆖', 'NG button'),
    Emoji('🅾️', 'O button (blood type)'),
    Emoji('🆗', 'OK button'),
    Emoji('🅿️', 'P button'),
    Emoji('🆘', 'SOS button'),
    Emoji('🆙', 'UP! button'),
    Emoji('🆚', 'VS button'),
    Emoji('🈁', 'Japanese “here” button'),
    Emoji('🈂️', 'Japanese “service charge” button'),
    Emoji('🈷️', 'Japanese “monthly amount” button'),
    Emoji('🈶', 'Japanese “not free of charge” button'),
    Emoji('🈯', 'Japanese “reserved” button'),
    Emoji('🉐', 'Japanese “bargain” button'),
    Emoji('🈹', 'Japanese “discount” button'),
    Emoji('🈚', 'Japanese “free of charge” button'),
    Emoji('🈲', 'Japanese “prohibited” button'),
    Emoji('🉑', 'Japanese “acceptable” button'),
    Emoji('🈸', 'Japanese “application” button'),
    Emoji('🈴', 'Japanese “passing grade” button'),
    Emoji('🈳', 'Japanese “vacancy” button'),
    Emoji('㊗️', 'Japanese “congratulations” button'),
    Emoji('㊙️', 'Japanese “secret” button'),
    Emoji('🈺', 'Japanese “open for business” button'),
    Emoji('🈵', 'Japanese “no vacancy” button'),
    Emoji('🔴', 'red circle'),
    Emoji('🟠', 'orange circle'),
    Emoji('🟡', 'yellow circle'),
    Emoji('🟢', 'green circle'),
    Emoji('🔵', 'blue circle'),
    Emoji('🟣', 'purple circle'),
    Emoji('🟤', 'brown circle'),
    Emoji('⚫', 'black circle'),
    Emoji('⚪', 'white circle'),
    Emoji('🟥', 'red square'),
    Emoji('🟧', 'orange square'),
    Emoji('🟨', 'yellow square'),
    Emoji('🟩', 'green square'),
    Emoji('🟦', 'blue square'),
    Emoji('🟪', 'purple square'),
    Emoji('🟫', 'brown square'),
    Emoji('⬛', 'black large square'),
    Emoji('⬜', 'white large square'),
    Emoji('◼️', 'black medium square'),
    Emoji('◻️', 'white medium square'),
    Emoji('◾', 'black medium-small square'),
    Emoji('◽', 'white medium-small square'),
    Emoji('▪️', 'black small square'),
    Emoji('▫️', 'white small square'),
    Emoji('🔶', 'large orange diamond'),
    Emoji('🔷', 'large blue diamond'),
    Emoji('🔸', 'small orange diamond'),
    Emoji('🔹', 'small blue diamond'),
    Emoji('🔺', 'red triangle pointed up'),
    Emoji('🔻', 'red triangle pointed down'),
    Emoji('💠', 'diamond with a dot'),
    Emoji('🔘', 'radio button'),
    Emoji('🔳', 'white square button'),
    Emoji('🔲', 'black square button'),
  ]),
  CategoryEmoji(Category.FLAGS, [
    Emoji('🏁', 'chequered flag'),
    Emoji('🚩', 'triangular flag'),
    Emoji('🎌', 'crossed flags'),
    Emoji('🏴', 'black flag'),
    Emoji('🏳️', 'white flag'),
    Emoji('🏳️‍🌈', 'rainbow flag'),
    Emoji('🏳️‍⚧️', 'transgender flag'),
    Emoji('🏴‍☠️', 'pirate flag'),
    Emoji('🇦🇨', 'flag: Ascension Island'),
    Emoji('🇦🇩', 'flag: Andorra'),
    Emoji('🇦🇪', 'flag: United Arab Emirates'),
    Emoji('🇦🇫', 'flag: Afghanistan'),
    Emoji('🇦🇬', 'flag: Antigua & Barbuda'),
    Emoji('🇦🇮', 'flag: Anguilla'),
    Emoji('🇦🇱', 'flag: Albania'),
    Emoji('🇦🇲', 'flag: Armenia'),
    Emoji('🇦🇴', 'flag: Angola'),
    Emoji('🇦🇶', 'flag: Antarctica'),
    Emoji('🇦🇷', 'flag: Argentina'),
    Emoji('🇦🇸', 'flag: American Samoa'),
    Emoji('🇦🇹', 'flag: Austria'),
    Emoji('🇦🇺', 'flag: Australia'),
    Emoji('🇦🇼', 'flag: Aruba'),
    Emoji('🇦🇽', 'flag: Åland Islands'),
    Emoji('🇦🇿', 'flag: Azerbaijan'),
    Emoji('🇧🇦', 'flag: Bosnia & Herzegovina'),
    Emoji('🇧🇧', 'flag: Barbados'),
    Emoji('🇧🇩', 'flag: Bangladesh'),
    Emoji('🇧🇪', 'flag: Belgium'),
    Emoji('🇧🇫', 'flag: Burkina Faso'),
    Emoji('🇧🇬', 'flag: Bulgaria'),
    Emoji('🇧🇭', 'flag: Bahrain'),
    Emoji('🇧🇮', 'flag: Burundi'),
    Emoji('🇧🇯', 'flag: Benin'),
    Emoji('🇧🇱', 'flag: St. Barthélemy'),
    Emoji('🇧🇲', 'flag: Bermuda'),
    Emoji('🇧🇳', 'flag: Brunei'),
    Emoji('🇧🇴', 'flag: Bolivia'),
    Emoji('🇧🇶', 'flag: Caribbean Netherlands'),
    Emoji('🇧🇷', 'flag: Brazil'),
    Emoji('🇧🇸', 'flag: Bahamas'),
    Emoji('🇧🇹', 'flag: Bhutan'),
    Emoji('🇧🇻', 'flag: Bouvet Island'),
    Emoji('🇧🇼', 'flag: Botswana'),
    Emoji('🇧🇾', 'flag: Belarus'),
    Emoji('🇧🇿', 'flag: Belize'),
    Emoji('🇨🇦', 'flag: Canada'),
    Emoji('🇨🇨', 'flag: Cocos (Keeling) Islands'),
    Emoji('🇨🇩', 'flag: Congo - Kinshasa'),
    Emoji('🇨🇫', 'flag: Central African Republic'),
    Emoji('🇨🇬', 'flag: Congo - Brazzaville'),
    Emoji('🇨🇭', 'flag: Switzerland'),
    Emoji('🇨🇮', 'flag: Côte d’Ivoire'),
    Emoji('🇨🇰', 'flag: Cook Islands'),
    Emoji('🇨🇱', 'flag: Chile'),
    Emoji('🇨🇲', 'flag: Cameroon'),
    Emoji('🇨🇳', 'flag: China'),
    Emoji('🇨🇴', 'flag: Colombia'),
    Emoji('🇨🇵', 'flag: Clipperton Island'),
    Emoji('🇨🇶', 'flag: Sark'),
    Emoji('🇨🇷', 'flag: Costa Rica'),
    Emoji('🇨🇺', 'flag: Cuba'),
    Emoji('🇨🇻', 'flag: Cape Verde'),
    Emoji('🇨🇼', 'flag: Curaçao'),
    Emoji('🇨🇽', 'flag: Christmas Island'),
    Emoji('🇨🇾', 'flag: Cyprus'),
    Emoji('🇨🇿', 'flag: Czechia'),
    Emoji('🇩🇪', 'flag: Germany'),
    Emoji('🇩🇬', 'flag: Diego Garcia'),
    Emoji('🇩🇯', 'flag: Djibouti'),
    Emoji('🇩🇰', 'flag: Denmark'),
    Emoji('🇩🇲', 'flag: Dominica'),
    Emoji('🇩🇴', 'flag: Dominican Republic'),
    Emoji('🇩🇿', 'flag: Algeria'),
    Emoji('🇪🇦', 'flag: Ceuta & Melilla'),
    Emoji('🇪🇨', 'flag: Ecuador'),
    Emoji('🇪🇪', 'flag: Estonia'),
    Emoji('🇪🇬', 'flag: Egypt'),
    Emoji('🇪🇭', 'flag: Western Sahara'),
    Emoji('🇪🇷', 'flag: Eritrea'),
    Emoji('🇪🇸', 'flag: Spain'),
    Emoji('🇪🇹', 'flag: Ethiopia'),
    Emoji('🇪🇺', 'flag: European Union'),
    Emoji('🇫🇮', 'flag: Finland'),
    Emoji('🇫🇯', 'flag: Fiji'),
    Emoji('🇫🇰', 'flag: Falkland Islands'),
    Emoji('🇫🇲', 'flag: Micronesia'),
    Emoji('🇫🇴', 'flag: Faroe Islands'),
    Emoji('🇫🇷', 'flag: France'),
    Emoji('🇬🇦', 'flag: Gabon'),
    Emoji('🇬🇧', 'flag: United Kingdom'),
    Emoji('🇬🇩', 'flag: Grenada'),
    Emoji('🇬🇪', 'flag: Georgia'),
    Emoji('🇬🇫', 'flag: French Guiana'),
    Emoji('🇬🇬', 'flag: Guernsey'),
    Emoji('🇬🇭', 'flag: Ghana'),
    Emoji('🇬🇮', 'flag: Gibraltar'),
    Emoji('🇬🇱', 'flag: Greenland'),
    Emoji('🇬🇲', 'flag: Gambia'),
    Emoji('🇬🇳', 'flag: Guinea'),
    Emoji('🇬🇵', 'flag: Guadeloupe'),
    Emoji('🇬🇶', 'flag: Equatorial Guinea'),
    Emoji('🇬🇷', 'flag: Greece'),
    Emoji('🇬🇸', 'flag: South Georgia & South Sandwich Islands'),
    Emoji('🇬🇹', 'flag: Guatemala'),
    Emoji('🇬🇺', 'flag: Guam'),
    Emoji('🇬🇼', 'flag: Guinea-Bissau'),
    Emoji('🇬🇾', 'flag: Guyana'),
    Emoji('🇭🇰', 'flag: Hong Kong SAR China'),
    Emoji('🇭🇲', 'flag: Heard & McDonald Islands'),
    Emoji('🇭🇳', 'flag: Honduras'),
    Emoji('🇭🇷', 'flag: Croatia'),
    Emoji('🇭🇹', 'flag: Haiti'),
    Emoji('🇭🇺', 'flag: Hungary'),
    Emoji('🇮🇨', 'flag: Canary Islands'),
    Emoji('🇮🇩', 'flag: Indonesia'),
    Emoji('🇮🇪', 'flag: Ireland'),
    Emoji('🇮🇱', 'flag: Israel'),
    Emoji('🇮🇲', 'flag: Isle of Man'),
    Emoji('🇮🇳', 'flag: India'),
    Emoji('🇮🇴', 'flag: British Indian Ocean Territory'),
    Emoji('🇮🇶', 'flag: Iraq'),
    Emoji('🇮🇷', 'flag: Iran'),
    Emoji('🇮🇸', 'flag: Iceland'),
    Emoji('🇮🇹', 'flag: Italy'),
    Emoji('🇯🇪', 'flag: Jersey'),
    Emoji('🇯🇲', 'flag: Jamaica'),
    Emoji('🇯🇴', 'flag: Jordan'),
    Emoji('🇯🇵', 'flag: Japan'),
    Emoji('🇰🇪', 'flag: Kenya'),
    Emoji('🇰🇬', 'flag: Kyrgyzstan'),
    Emoji('🇰🇭', 'flag: Cambodia'),
    Emoji('🇰🇮', 'flag: Kiribati'),
    Emoji('🇰🇲', 'flag: Comoros'),
    Emoji('🇰🇳', 'flag: St. Kitts & Nevis'),
    Emoji('🇰🇵', 'flag: North Korea'),
    Emoji('🇰🇷', 'flag: South Korea'),
    Emoji('🇰🇼', 'flag: Kuwait'),
    Emoji('🇰🇾', 'flag: Cayman Islands'),
    Emoji('🇰🇿', 'flag: Kazakhstan'),
    Emoji('🇱🇦', 'flag: Laos'),
    Emoji('🇱🇧', 'flag: Lebanon'),
    Emoji('🇱🇨', 'flag: St. Lucia'),
    Emoji('🇱🇮', 'flag: Liechtenstein'),
    Emoji('🇱🇰', 'flag: Sri Lanka'),
    Emoji('🇱🇷', 'flag: Liberia'),
    Emoji('🇱🇸', 'flag: Lesotho'),
    Emoji('🇱🇹', 'flag: Lithuania'),
    Emoji('🇱🇺', 'flag: Luxembourg'),
    Emoji('🇱🇻', 'flag: Latvia'),
    Emoji('🇱🇾', 'flag: Libya'),
    Emoji('🇲🇦', 'flag: Morocco'),
    Emoji('🇲🇨', 'flag: Monaco'),
    Emoji('🇲🇩', 'flag: Moldova'),
    Emoji('🇲🇪', 'flag: Montenegro'),
    Emoji('🇲🇫', 'flag: St. Martin'),
    Emoji('🇲🇬', 'flag: Madagascar'),
    Emoji('🇲🇭', 'flag: Marshall Islands'),
    Emoji('🇲🇰', 'flag: North Macedonia'),
    Emoji('🇲🇱', 'flag: Mali'),
    Emoji('🇲🇲', 'flag: Myanmar (Burma)'),
    Emoji('🇲🇳', 'flag: Mongolia'),
    Emoji('🇲🇴', 'flag: Macao SAR China'),
    Emoji('🇲🇵', 'flag: Northern Mariana Islands'),
    Emoji('🇲🇶', 'flag: Martinique'),
    Emoji('🇲🇷', 'flag: Mauritania'),
    Emoji('🇲🇸', 'flag: Montserrat'),
    Emoji('🇲🇹', 'flag: Malta'),
    Emoji('🇲🇺', 'flag: Mauritius'),
    Emoji('🇲🇻', 'flag: Maldives'),
    Emoji('🇲🇼', 'flag: Malawi'),
    Emoji('🇲🇽', 'flag: Mexico'),
    Emoji('🇲🇾', 'flag: Malaysia'),
    Emoji('🇲🇿', 'flag: Mozambique'),
    Emoji('🇳🇦', 'flag: Namibia'),
    Emoji('🇳🇨', 'flag: New Caledonia'),
    Emoji('🇳🇪', 'flag: Niger'),
    Emoji('🇳🇫', 'flag: Norfolk Island'),
    Emoji('🇳🇬', 'flag: Nigeria'),
    Emoji('🇳🇮', 'flag: Nicaragua'),
    Emoji('🇳🇱', 'flag: Netherlands'),
    Emoji('🇳🇴', 'flag: Norway'),
    Emoji('🇳🇵', 'flag: Nepal'),
    Emoji('🇳🇷', 'flag: Nauru'),
    Emoji('🇳🇺', 'flag: Niue'),
    Emoji('🇳🇿', 'flag: New Zealand'),
    Emoji('🇴🇲', 'flag: Oman'),
    Emoji('🇵🇦', 'flag: Panama'),
    Emoji('🇵🇪', 'flag: Peru'),
    Emoji('🇵🇫', 'flag: French Polynesia'),
    Emoji('🇵🇬', 'flag: Papua New Guinea'),
    Emoji('🇵🇭', 'flag: Philippines'),
    Emoji('🇵🇰', 'flag: Pakistan'),
    Emoji('🇵🇱', 'flag: Poland'),
    Emoji('🇵🇲', 'flag: St. Pierre & Miquelon'),
    Emoji('🇵🇳', 'flag: Pitcairn Islands'),
    Emoji('🇵🇷', 'flag: Puerto Rico'),
    Emoji('🇵🇸', 'flag: Palestinian Territories'),
    Emoji('🇵🇹', 'flag: Portugal'),
    Emoji('🇵🇼', 'flag: Palau'),
    Emoji('🇵🇾', 'flag: Paraguay'),
    Emoji('🇶🇦', 'flag: Qatar'),
    Emoji('🇷🇪', 'flag: Réunion'),
    Emoji('🇷🇴', 'flag: Romania'),
    Emoji('🇷🇸', 'flag: Serbia'),
    Emoji('🇷🇺', 'flag: Russia'),
    Emoji('🇷🇼', 'flag: Rwanda'),
    Emoji('🇸🇦', 'flag: Saudi Arabia'),
    Emoji('🇸🇧', 'flag: Solomon Islands'),
    Emoji('🇸🇨', 'flag: Seychelles'),
    Emoji('🇸🇩', 'flag: Sudan'),
    Emoji('🇸🇪', 'flag: Sweden'),
    Emoji('🇸🇬', 'flag: Singapore'),
    Emoji('🇸🇭', 'flag: St. Helena'),
    Emoji('🇸🇮', 'flag: Slovenia'),
    Emoji('🇸🇯', 'flag: Svalbard & Jan Mayen'),
    Emoji('🇸🇰', 'flag: Slovakia'),
    Emoji('🇸🇱', 'flag: Sierra Leone'),
    Emoji('🇸🇲', 'flag: San Marino'),
    Emoji('🇸🇳', 'flag: Senegal'),
    Emoji('🇸🇴', 'flag: Somalia'),
    Emoji('🇸🇷', 'flag: Suriname'),
    Emoji('🇸🇸', 'flag: South Sudan'),
    Emoji('🇸🇹', 'flag: São Tomé & Príncipe'),
    Emoji('🇸🇻', 'flag: El Salvador'),
    Emoji('🇸🇽', 'flag: Sint Maarten'),
    Emoji('🇸🇾', 'flag: Syria'),
    Emoji('🇸🇿', 'flag: Eswatini'),
    Emoji('🇹🇦', 'flag: Tristan da Cunha'),
    Emoji('🇹🇨', 'flag: Turks & Caicos Islands'),
    Emoji('🇹🇩', 'flag: Chad'),
    Emoji('🇹🇫', 'flag: French Southern Territories'),
    Emoji('🇹🇬', 'flag: Togo'),
    Emoji('🇹🇭', 'flag: Thailand'),
    Emoji('🇹🇯', 'flag: Tajikistan'),
    Emoji('🇹🇰', 'flag: Tokelau'),
    Emoji('🇹🇱', 'flag: Timor-Leste'),
    Emoji('🇹🇲', 'flag: Turkmenistan'),
    Emoji('🇹🇳', 'flag: Tunisia'),
    Emoji('🇹🇴', 'flag: Tonga'),
    Emoji('🇹🇷', 'flag: Türkiye'),
    Emoji('🇹🇹', 'flag: Trinidad & Tobago'),
    Emoji('🇹🇻', 'flag: Tuvalu'),
    Emoji('🇹🇼', 'flag: Taiwan'),
    Emoji('🇹🇿', 'flag: Tanzania'),
    Emoji('🇺🇦', 'flag: Ukraine'),
    Emoji('🇺🇬', 'flag: Uganda'),
    Emoji('🇺🇲', 'flag: U.S. Outlying Islands'),
    Emoji('🇺🇳', 'flag: United Nations'),
    Emoji('🇺🇸', 'flag: United States'),
    Emoji('🇺🇾', 'flag: Uruguay'),
    Emoji('🇺🇿', 'flag: Uzbekistan'),
    Emoji('🇻🇦', 'flag: Vatican City'),
    Emoji('🇻🇨', 'flag: St. Vincent & Grenadines'),
    Emoji('🇻🇪', 'flag: Venezuela'),
    Emoji('🇻🇬', 'flag: British Virgin Islands'),
    Emoji('🇻🇮', 'flag: U.S. Virgin Islands'),
    Emoji('🇻🇳', 'flag: Vietnam'),
    Emoji('🇻🇺', 'flag: Vanuatu'),
    Emoji('🇼🇫', 'flag: Wallis & Futuna'),
    Emoji('🇼🇸', 'flag: Samoa'),
    Emoji('🇽🇰', 'flag: Kosovo'),
    Emoji('🇾🇪', 'flag: Yemen'),
    Emoji('🇾🇹', 'flag: Mayotte'),
    Emoji('🇿🇦', 'flag: South Africa'),
    Emoji('🇿🇲', 'flag: Zambia'),
    Emoji('🇿🇼', 'flag: Zimbabwe'),
    Emoji('🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'flag: England'),
    Emoji('🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'flag: Scotland'),
    Emoji('🏴󠁧󠁢󠁷󠁬󠁳󠁿', 'flag: Wales'),
  ]),
];
