import 'dart:io';

/// Shared helpers for parsing and normalizing HTTPDNS domain settings.
abstract final class HttpDnsDomainHelper {
  static const int maxKeepAliveDomains = 10;

  /// Parses editable text input into a normalized domain list.
  ///
  /// Parameters:
  ///   input: The raw text entered by the user.
  /// Returns:
  ///   A de-duplicated list of normalized host names.
  static List<String> parseEditableInput(String input) =>
      normalizeDomains(input.split(RegExp(r'[\s,;]+')));

  /// Converts a stored domain list into editable multi-line text.
  ///
  /// Parameters:
  ///   domains: The stored domains to render.
  /// Returns:
  ///   A newline-separated string for the editor dialog.
  static String toEditableInput(Iterable<String> domains) =>
      normalizeDomains(domains).join('\n');

  /// Normalizes a collection of domain-like strings.
  ///
  /// Parameters:
  ///   rawDomains: Raw user or app-provided domain values.
  /// Returns:
  ///   A de-duplicated list of lowercase host names without schemes or ports.
  static List<String> normalizeDomains(Iterable<String> rawDomains) {
    final normalizedDomains = <String>[];
    final seenDomains = <String>{};

    for (final rawDomain in rawDomains) {
      final normalizedDomain = _normalizeSingleDomain(rawDomain);
      if (normalizedDomain == null || !seenDomains.add(normalizedDomain)) {
        continue;
      }
      normalizedDomains.add(normalizedDomain);
    }

    return normalizedDomains;
  }

  /// Merges managed homeserver domains with user-configured domains.
  ///
  /// Parameters:
  ///   managedDomains: Domains automatically derived from configured homeservers.
  ///   userDomains: Domains explicitly configured by the user.
  /// Returns:
  ///   A de-duplicated list that keeps managed domains first.
  static List<String> mergeDomains(
    Iterable<String> managedDomains,
    Iterable<String> userDomains,
  ) => normalizeDomains([...managedDomains, ...userDomains]);

  /// Applies Aliyun's keep-alive domain cap while prioritizing homeserver hosts.
  ///
  /// Parameters:
  ///   managedDomains: Auto-managed homeserver domains that should take priority.
  ///   userDomains: User-configured keep-alive domains.
  ///   maxDomains: Maximum number of domains supported by the native SDK.
  /// Returns:
  ///   A trimmed list with homeserver domains preserved first.
  static List<String> limitKeepAliveDomains({
    required Iterable<String> managedDomains,
    required Iterable<String> userDomains,
    int maxDomains = maxKeepAliveDomains,
  }) => mergeDomains(managedDomains, userDomains).take(maxDomains).toList();

  /// Normalizes one user-provided domain-like value.
  ///
  /// Parameters:
  ///   rawDomain: The raw value entered by the user or generated by the app.
  /// Returns:
  ///   A host name, or null if the input cannot be used for HTTPDNS.
  static String? _normalizeSingleDomain(String rawDomain) {
    final trimmedDomain = rawDomain.trim();
    if (trimmedDomain.isEmpty) {
      return null;
    }

    String? hostName;
    final directUri = Uri.tryParse(trimmedDomain);
    if (directUri != null && directUri.host.isNotEmpty) {
      hostName = directUri.host;
    } else {
      hostName = Uri.tryParse('https://$trimmedDomain')?.host;
    }

    final normalizedHost = hostName?.trim().toLowerCase();
    if (normalizedHost == null || normalizedHost.isEmpty) {
      return null;
    }
    if (InternetAddress.tryParse(normalizedHost) != null) {
      return null;
    }

    return normalizedHost.replaceAll(RegExp(r'\.+$'), '');
  }
}
